# GENERATED by moe-mint — edit moe-mint.yaml instead
import os
import re
import sys
from pathlib import Path

BOOTSTRAP_MARKER = '<plugin-bootstrap plugin="moe-everything">'


def _skills_dir():
    """Locate the skills/ tree for either supported install layout,
    returning (skills_dir, plugin_root).

    - git-clone install: `.hermes-plugin/` and `skills/` are
      siblings under the plugin root, so this module resolves
      `../skills` (plugin_root = one level up from this file).
    - flattened install: `skills/` sits next to this module
      (plugin_root = this file's directory).

    Raises loudly when neither matches -- a bootstrap that silently skips
    is how a broken install masquerades as a working one.
    """
    here = os.path.dirname(os.path.realpath(__file__))
    candidates = (
        (os.path.realpath(os.path.join(here, "..", *"skills".split("/"))), os.path.realpath(os.path.join(here, ".."))),
        (os.path.realpath(os.path.join(here, *"skills".split("/"))), here),
    )
    for skills_dir, plugin_root in candidates:
        if os.path.isdir(skills_dir):
            return skills_dir, plugin_root
    raise RuntimeError(
        "moe-everything plugin: cannot find the skills/ tree "
        f"(looked at {[c[0] for c in candidates]})."
    )


def _strip_frontmatter(content: str) -> str:
    match = re.match(r"^---\n[\s\S]*?\n---\n([\s\S]*)$", content)
    return (match.group(1) if match else content).strip()


def _build_bootstrap(plugin_root: str) -> str:
    bootstrap_path = os.path.join(plugin_root, *"skills/using-moe/SKILL.md".split("/"))
    with open(bootstrap_path, encoding="utf-8") as f:
        body = _strip_frontmatter(f.read())
    return (
        f"{BOOTSTRAP_MARKER}\n"
        "This plugin's bootstrap content is included below and is already "
        "loaded for this session. Follow it now.\n\n"
        f"{body}\n"
        "</plugin-bootstrap>"
    )


def register(ctx):
    skills_dir, plugin_root = _skills_dir()

    # Register every skill with Hermes' native loader so skill_view can
    # load it on demand. Skills are registered before the bootstrap is
    # built below so a broken bootstrap can never take skill registration
    # down with it.
    # register_skill requires a pathlib.Path — a str raises AttributeError and
    # hermes silently disables the whole plugin (verified 2026-07-23).
    for name in sorted(os.listdir(skills_dir)):
        skill_md = os.path.join(skills_dir, name, "SKILL.md")
        if os.path.isfile(skill_md):
            ctx.register_skill(name, Path(skill_md))

    # The bootstrap file is a separate, less load-bearing concern than the
    # skills registered above -- a missing or unreadable bootstrap should
    # degrade to "skills work, no session bootstrap" rather than disabling
    # the whole plugin.
    try:
        bootstrap = _build_bootstrap(plugin_root)
    except Exception as e:
        print(
            f"moe-everything plugin: bootstrap unavailable ({e}); "
            "skills registered without session bootstrap",
            file=sys.stderr,
        )
        return

    # pre_llm_call returning {"context": ...} is the documented injection
    # path; the context is appended to the first turn's user message.
    def pre_llm_call(
        session_id=None,
        user_message=None,
        conversation_history=None,
        is_first_turn=None,
        model=None,
        platform=None,
        **kwargs,
    ):
        if is_first_turn:
            return {"context": bootstrap}
        return None

    ctx.register_hook("pre_llm_call", pre_llm_call)
