# GENERATED by moe-mint — edit moe-mint.yaml instead
import os
from pathlib import Path


def _skills_dir():
    """Locate the skills/ tree for either supported install layout,
    returning (skills_dir, plugin_root).

    - git-clone install: `.hermes-plugin/` and `skills/` are
      siblings under the plugin root, so this module resolves
      `../skills` (plugin_root = one level up from this file).
    - flattened install: `skills/` sits next to this module
      (plugin_root = this file's directory).

    Raises loudly when neither matches -- a bootstrap that silently skips
    is how a broken install masquerades as a working one.
    """
    here = os.path.dirname(os.path.realpath(__file__))
    candidates = (
        (os.path.realpath(os.path.join(here, "..", *"skills".split("/"))), os.path.realpath(os.path.join(here, ".."))),
        (os.path.realpath(os.path.join(here, *"skills".split("/"))), here),
    )
    for skills_dir, plugin_root in candidates:
        if os.path.isdir(skills_dir):
            return skills_dir, plugin_root
    raise RuntimeError(
        "moe-backstory plugin: cannot find the skills/ tree "
        f"(looked at {[c[0] for c in candidates]})."
    )


def register(ctx):
    skills_dir, _plugin_root = _skills_dir()

    # Register every skill with Hermes' native loader so skill_view can
    # load it on demand.
    # register_skill requires a pathlib.Path — a str raises AttributeError and
    # hermes silently disables the whole plugin (verified 2026-07-23).
    for name in sorted(os.listdir(skills_dir)):
        skill_md = os.path.join(skills_dir, name, "SKILL.md")
        if os.path.isfile(skill_md):
            ctx.register_skill(name, Path(skill_md))
