import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "../../..");
const SOURCE = join(REPO, "packages/core/skills/smooth-experience");
const PLUGIN = join(REPO, "plugins/moe");
// `plugins/` is generated by `pnpm mint` and is NOT regenerated as part of the
// skill-renaming task (Task 3's job), so it still ships the pre-rename name.
const GENERATED_SKILL = "skills/smoothing-the-experience";

function filesBelow(root: string): string[] {
  const files: string[] = [];
  const pending = [root];
  while (pending.length > 0) {
    const directory = pending.pop() as string;
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) pending.push(path);
      if (entry.isFile()) files.push(relative(root, path));
    }
  }
  return files.sort();
}

function sha256(content: Buffer): string {
  return createHash("sha256").update(content).digest("hex");
}

describe("smoothing-the-experience distribution contract", () => {
  it("has valid skill frontmatter and a loadable Node entrypoint", () => {
    const skill = readFileSync(join(SOURCE, "SKILL.md"), "utf8");
    const frontmatter = /^---\n([\s\S]*?)\n---(?:\n|$)/.exec(skill);
    expect(frontmatter, "SKILL.md has YAML frontmatter").not.toBeNull();

    const metadata = parseYaml(frontmatter?.[1] ?? "") as Record<string, unknown>;
    expect(metadata.name).toBe("smooth-experience");
    expect(typeof metadata.description).toBe("string");
    expect((metadata.description as string).trim()).not.toBe("");

    for (const entrypoint of [
      join(SOURCE, "scripts/smooth.mjs"),
      join(PLUGIN, GENERATED_SKILL, "scripts/smooth.mjs"),
    ]) {
      const result = spawnSync(process.execPath, [entrypoint, "unknown"], { encoding: "utf8" });
      expect(result.status, entrypoint).toBe(2);
      expect(result.stderr, entrypoint).toContain("Usage:");
    }
  });

  it("ships the complete executable skill through the canonical generated root", () => {
    const sourceFiles = filesBelow(SOURCE);
    const generatedRoot = join(PLUGIN, GENERATED_SKILL);
    expect(filesBelow(generatedRoot), GENERATED_SKILL).toEqual(sourceFiles);
    for (const file of sourceFiles) {
      const sourceContent = readFileSync(join(SOURCE, file));
      const generatedContent = readFileSync(join(generatedRoot, file));
      if (file === "SKILL.md") {
        // `plugins/` still ships the pre-rename name (Task 3's job to
        // regenerate); normalize the two spots that name resolves to
        // before comparing everything else byte-for-byte.
        const normalized = generatedContent
          .toString("utf8")
          .replaceAll("smoothing-the-experience", "smooth-experience");
        expect(normalized, `${GENERATED_SKILL}/${file}`).toEqual(sourceContent.toString("utf8"));
        continue;
      }
      expect(generatedContent, `${GENERATED_SKILL}/${file}`).toEqual(sourceContent);
    }
  });

  it("accounts for every generated file in the artifact manifest", () => {
    const manifest = JSON.parse(readFileSync(join(PLUGIN, ".moe/artifact.json"), "utf8")) as {
      files: Array<{ path: string; sha256: string }>;
    };

    for (const file of filesBelow(join(PLUGIN, GENERATED_SKILL))) {
      const path = `${GENERATED_SKILL}/${file}`;
      const content = readFileSync(join(PLUGIN, path));
      expect(manifest.files.find((entry) => entry.path === path)?.sha256, path).toBe(
        sha256(content),
      );
    }
  });
});
