import { describe, it, expect } from 'vitest'
import { byPathMap, mustGet } from '../helpers.js'
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { buildModel } from '../../src/model.js'
import { gemini } from '../../src/adapters/gemini.js'
import { adapters, getAdapter } from '../../src/adapters/index.js'

const model = buildModel('fixtures/kitchen-sink')

function tmpFixture(yaml: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'mint-gemini-cmd-'))
  writeFileSync(join(dir, 'moe-mint.yaml'), yaml)
  return dir
}

// Parses an emitted TOML command file with `python3 -c "import tomllib; ..."`
// -- proves the emitted content is not just string-matched but actually
// valid TOML per the ground-truth spec. tomllib ships in the stdlib from
// Python 3.11; TOMLLIB_AVAILABLE gates the tests that call this so the suite
// degrades to a skip (not a failure) on an older python3.
function tomlParse(content: string): Record<string, unknown> {
  const dir = mkdtempSync(join(tmpdir(), 'mint-gemini-toml-'))
  const filePath = join(dir, 'cmd.toml')
  writeFileSync(filePath, content)
  const stdout = execFileSync(
    'python3',
    ['-c', 'import json, tomllib, sys\nwith open(sys.argv[1], "rb") as f:\n    print(json.dumps(tomllib.load(f)))', filePath],
    { encoding: 'utf8' },
  )
  return JSON.parse(stdout)
}

const TOMLLIB_AVAILABLE = (() => {
  try {
    execFileSync('python3', ['-c', 'import tomllib'], { stdio: 'pipe' })
    return true
  } catch {
    return false
  }
})()

if (!TOMLLIB_AVAILABLE) {
  console.warn('python3 tomllib unavailable (needs Python >= 3.11) -- skipping TOML validity checks in gemini.test.ts')
}

describe('adapter registry', () => {
  it('registers gemini', () => {
    expect(adapters.map((a) => a.name)).toContain('gemini')
    expect(getAdapter('gemini')).toBe(gemini)
  })
})

describe('gemini adapter', () => {
  const result = gemini.emit(model)
  const byPath = byPathMap(result.files)

  it('emits gemini-extension.json with the exact ground-truth shape', () => {
    const manifest = JSON.parse(mustGet(byPath, 'gemini-extension.json'))
    expect(manifest).toEqual({
      name: 'kitchen-sink',
      description: 'Fixture plugin exercising every component type',
      version: '0.1.0',
      contextFileName: 'GEMINI.md',
    })
  })

  it('emits GEMINI.md with the marker and the bootstrap skill @-include', () => {
    expect(mustGet(byPath, 'GEMINI.md')).toBe(
      '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->\n\n@./skills/using-kitchen-sink/SKILL.md\n',
    )
  })

  it('warns about hooks, agents, and mcp not being emitted for gemini (commands are now translated)', () => {
    expect(result.warnings).toEqual([
      'hooks are not emitted for gemini',
      'agents are not emitted for gemini',
      'mcp servers are not emitted for gemini in v1 (Plan 3)',
    ])
  })

  it('declares expected support levels', () => {
    expect(gemini.support).toEqual({
      skills: 'full',
      commands: 'full',
      agents: 'none',
      hooks: 'none',
      mcp: 'none',
      bootstrap: 'full',
    })
  })

  it('emits commands/ks-hello.toml with the exact ground-truth shape', () => {
    expect(mustGet(byPath, 'commands/ks-hello.toml')).toBe(
      '# GENERATED by moe-mint — edit moe-mint.yaml instead\n' +
        'description = "Say hello from the kitchen-sink fixture"\n' +
        'prompt = """\n' +
        '\n' +
        'Say a cheerful hello to {{args}} (default: the current user).\n' +
        '"""\n',
    )
  })

  it('emits a commands/ks-hello.toml with a well-formed TOML structure', () => {
    const toml = mustGet(byPath, 'commands/ks-hello.toml')
    const lines = toml.split('\n')
    expect(lines[0]).toBe('# GENERATED by moe-mint — edit moe-mint.yaml instead')
    expect(lines[1]).toMatch(/^description = "[^\n]*"$/)
    expect(lines[2]).toBe('prompt = """')
    expect(toml.endsWith('"""\n')).toBe(true)
  })

  it.skipIf(!TOMLLIB_AVAILABLE)('commands/ks-hello.toml parses with python3 tomllib to the expected value', () => {
    const parsed = tomlParse(mustGet(byPath, 'commands/ks-hello.toml'))
    expect(parsed).toEqual({
      description: 'Say hello from the kitchen-sink fixture',
      prompt: '\nSay a cheerful hello to {{args}} (default: the current user).\n',
    })
  })
})

describe('gemini adapter with harnesses.gemini.manifest', () => {
  it('deep-merges override fields into gemini-extension.json', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-gemini-override-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      [
        'name: override-demo',
        'version: 1.0.0',
        'description: override fixture for gemini extension metadata',
        'harnesses:',
        '  gemini:',
        '    manifest:',
        '      contextFileName: CUSTOM.md',
      ].join('\n'),
    )
    const overrideModel = buildModel(dir)
    const result = gemini.emit(overrideModel)
    const manifest = JSON.parse(result.files.find((f) => f.path === 'gemini-extension.json')!.content)
    expect(manifest.contextFileName).toBe('CUSTOM.md')
  })

  it('warns that a contextFileName override does not match the emitted GEMINI.md', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-gemini-override-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      [
        'name: override-demo',
        'version: 1.0.0',
        'description: override fixture for gemini extension metadata',
        'harnesses:',
        '  gemini:',
        '    manifest:',
        '      contextFileName: CUSTOM.md',
      ].join('\n'),
    )
    const overrideModel = buildModel(dir)
    const result = gemini.emit(overrideModel)
    expect(result.warnings).toContain(
      'contextFileName override "CUSTOM.md" does not match the emitted GEMINI.md; the harness will look for a missing file',
    )
  })
})

describe('gemini adapter without a bootstrap skill', () => {
  it('emits GEMINI.md with a skills-location note and no @-include', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-gemini-none-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      'name: no-bootstrap\nversion: 1.0.0\ndescription: no bootstrap fixture\nbootstrap: none\n',
    )
    mkdirSync(join(dir, 'skills', 'demo'), { recursive: true })
    writeFileSync(
      join(dir, 'skills', 'demo', 'SKILL.md'),
      '---\nname: demo\ndescription: demo skill for gemini none-mode test\n---\n\nBody.\n',
    )
    const noneModel = buildModel(dir)
    const result = gemini.emit(noneModel)
    const geminiMd = result.files.find((f) => f.path === 'GEMINI.md')!.content
    expect(geminiMd).toContain('This plugin provides skills in skills/.')
    expect(geminiMd).not.toContain('@./')
  })
})

describe('gemini adapter with bootstrap.generate', () => {
  it('emits GEMINI.md @-including the generated bootstrap.md, and the file itself', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-gemini-generate-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      'name: generate-bootstrap\nversion: 1.0.0\ndescription: bootstrap.generate fixture\nbootstrap: generate\n',
    )
    const generateModel = buildModel(dir)
    const result = gemini.emit(generateModel)
    const geminiMd = result.files.find((f) => f.path === 'GEMINI.md')!.content
    expect(geminiMd).toBe(
      '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->\n\n@./hooks/moe-mint/bootstrap.md\n',
    )
    const bootstrapMd = result.files.find((f) => f.path === 'hooks/moe-mint/bootstrap.md')
    expect(bootstrapMd?.content).toContain('# generate-bootstrap plugin')
  })
})

describe('gemini TOML command translation: positional arguments', () => {
  it.skipIf(!TOMLLIB_AVAILABLE)('warns and still emits the command, leaving $1 verbatim and swapping $ARGUMENTS', () => {
    const dir = tmpFixture(
      'name: positional-demo\nversion: 1.0.0\ndescription: positional-args fixture\nbootstrap: none\n',
    )
    mkdirSync(join(dir, 'commands'), { recursive: true })
    writeFileSync(
      join(dir, 'commands', 'explain.md'),
      '---\ndescription: Explain a topic\n---\nExplain $1 to $ARGUMENTS.\n',
    )
    const posModel = buildModel(dir)
    const result = gemini.emit(posModel)

    expect(result.warnings).toContain(
      'command "explain" uses positional arguments; Gemini supports only {{args}} — positional syntax passed through verbatim',
    )
    const toml = result.files.find((f) => f.path === 'commands/explain.toml')!.content
    expect(toml).toContain('Explain $1 to {{args}}.')
    expect(tomlParse(toml).prompt).toBe('Explain $1 to {{args}}.\n')
  })
})

describe('gemini TOML command translation: description escaping', () => {
  it.skipIf(!TOMLLIB_AVAILABLE)('escapes backslash and double-quote in the description and round-trips through tomllib', () => {
    const dir = tmpFixture(
      'name: escape-demo\nversion: 1.0.0\ndescription: description-escaping fixture\nbootstrap: none\n',
    )
    mkdirSync(join(dir, 'commands'), { recursive: true })
    writeFileSync(
      join(dir, 'commands', 'quoted.md'),
      '---\ndescription: say "hi" \\now\n---\n\nBody.\n',
    )
    const escModel = buildModel(dir)
    const result = gemini.emit(escModel)
    const toml = result.files.find((f) => f.path === 'commands/quoted.toml')!.content

    expect(toml).toContain('description = "say \\"hi\\" \\\\now"')
    expect(tomlParse(toml).description).toBe('say "hi" \\now')
  })
})

describe('gemini TOML command translation: embedded triple quotes', () => {
  it.skipIf(!TOMLLIB_AVAILABLE)('warns, escapes the triple quotes, and still parses as valid TOML round-tripping the original body', () => {
    const dir = tmpFixture(
      'name: triple-demo\nversion: 1.0.0\ndescription: triple-quote fixture\nbootstrap: none\n',
    )
    mkdirSync(join(dir, 'commands'), { recursive: true })
    writeFileSync(
      join(dir, 'commands', 'delim.md'),
      '---\ndescription: Uses a literal delimiter\n---\nUse """ as a delimiter please.\n',
    )
    const tripleModel = buildModel(dir)
    const result = gemini.emit(tripleModel)

    expect(result.warnings).toContain('command "delim" body contains triple quotes; escaped for TOML')
    const toml = result.files.find((f) => f.path === 'commands/delim.toml')!.content
    expect(toml).not.toContain('"""\n"""\n"""') // sanity: not three raw unescaped delimiters in a row
    expect(tomlParse(toml).prompt).toBe('Use """ as a delimiter please.\n')
  })
})

describe('gemini TOML command translation: backslash escaping in body', () => {
  it.skipIf(!TOMLLIB_AVAILABLE)('escapes backslashes in the body and round-trips through tomllib to the original body', () => {
    const dir = tmpFixture(
      'name: backslash-demo\nversion: 1.0.0\ndescription: backslash-body fixture\nbootstrap: none\n',
    )
    mkdirSync(join(dir, 'commands'), { recursive: true })
    const originalBody = "Run grep '\\d+' and C:\\path please.\n"
    writeFileSync(
      join(dir, 'commands', 'slash.md'),
      `---\ndescription: Backslash body test\n---\n${originalBody}`,
    )
    const slashModel = buildModel(dir)
    const result = gemini.emit(slashModel)
    const toml = result.files.find((f) => f.path === 'commands/slash.toml')!.content

    const parsed = tomlParse(toml)
    expect(parsed.prompt).toBe(originalBody)
  })
})

describe('gemini TOML command translation: bootstrap-mode independence', () => {
  it('still emits commands/*.toml under bootstrap.generate and bootstrap: none', () => {
    for (const bootstrapYaml of ['bootstrap: generate\n', 'bootstrap: none\n']) {
      const dir = tmpFixture(`name: mode-demo\nversion: 1.0.0\ndescription: bootstrap-mode fixture\n${bootstrapYaml}`)
      mkdirSync(join(dir, 'commands'), { recursive: true })
      writeFileSync(join(dir, 'commands', 'ping.md'), '---\ndescription: Ping\n---\n\nPing $ARGUMENTS.\n')
      const modeModel = buildModel(dir)
      const result = gemini.emit(modeModel)
      const toml = result.files.find((f) => f.path === 'commands/ping.toml')
      expect(toml).toBeDefined()
      expect(toml!.content).toContain('prompt = """')
    }
  })
})

describe('gemini TOML command translation: word-boundary preservation', () => {
  it.skipIf(!TOMLLIB_AVAILABLE)('replaces standalone $ARGUMENTS but preserves $ARGUMENTSX (longer token)', () => {
    const dir = tmpFixture(
      'name: word-boundary-demo\nversion: 1.0.0\ndescription: word-boundary fixture\nbootstrap: none\n',
    )
    mkdirSync(join(dir, 'commands'), { recursive: true })
    writeFileSync(
      join(dir, 'commands', 'mixed.md'),
      '---\ndescription: Mixed arguments token test\n---\n\nUse $ARGUMENTSX and $ARGUMENTS.\n',
    )
    const boundaryModel = buildModel(dir)
    const result = gemini.emit(boundaryModel)
    const toml = result.files.find((f) => f.path === 'commands/mixed.toml')!.content

    expect(toml).toContain('$ARGUMENTSX') // longer token unchanged
    expect(toml).toContain('{{args}}.') // standalone token replaced

    const parsed = tomlParse(toml)
    expect(parsed.prompt).toBe('\nUse $ARGUMENTSX and {{args}}.\n')
  })
})
