import { describe, it, expect } from 'vitest'
import { byPathMap, mustGet } from '../helpers.js'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync, spawnSync } from 'node:child_process'
import { parse } from 'yaml'
import { buildModel } from '../../src/model.js'
import { writeFileSet } from '../../src/fileset.js'
import { hermes } from '../../src/adapters/hermes.js'
import { adapters, getAdapter } from '../../src/adapters/index.js'
import { GENERATED_BOOTSTRAP_PATH } from '../../src/bootstrap/generated.js'

const model = buildModel('fixtures/kitchen-sink')

function tmpFixture(yaml: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'mint-hermes-'))
  writeFileSync(join(dir, 'moe-mint.yaml'), yaml)
  return dir
}

// Compiles an emitted __init__.py with `python3 -m py_compile` -- proves the
// generated Python is at least syntactically valid, not just string-matched.
function pyCompile(source: string): { status: number | null } {
  const dir = mkdtempSync(join(tmpdir(), 'mint-hermes-pyc-'))
  const filePath = join(dir, '__init__.py')
  writeFileSync(filePath, source)
  try {
    execFileSync('python3', ['-m', 'py_compile', filePath], { stdio: 'pipe' })
    return { status: 0 }
  } catch (error) {
    return { status: (error as { status: number | null }).status }
  }
}

describe('adapter registry', () => {
  it('registers hermes between pi and agent-plugins-1.0', () => {
    const names = adapters.map((a) => a.name)
    expect(names).toContain('hermes')
    expect(getAdapter('hermes')).toBe(hermes)
    expect(names.indexOf('hermes')).toBe(names.indexOf('pi') + 1)
    expect(names.indexOf('hermes')).toBe(names.indexOf('agent-plugins-1.0') - 1)
  })
})

describe('hermes adapter', () => {
  const result = hermes.emit(model)
  const byPath = byPathMap(result.files)

  it('declares expected support levels', () => {
    expect(hermes.support).toEqual({
      skills: 'full',
      commands: 'none',
      agents: 'none',
      hooks: 'none',
      mcp: 'none',
      bootstrap: 'full',
    })
  })

  it('warns about commands, agents, hooks, and mcp', () => {
    expect(result.warnings).toEqual([
      'commands are not emitted for hermes',
      'agents are not emitted for hermes',
      'hooks are not emitted for hermes',
      'mcp servers are not emitted for hermes',
    ])
  })

  describe('plugin.yaml', () => {
    const content = mustGet(byPath, '.hermes-plugin/plugin.yaml')

    it('has the marker as line 1', () => {
      expect(content.split('\n')[0]).toBe('# GENERATED by moe-mint — edit moe-mint.yaml instead')
    })

    it('yaml-parses to the exact ground-truth shape', () => {
      const lines = content.split('\n')
      const rest = lines.slice(1).join('\n')
      expect(parse(rest)).toEqual({
        name: 'kitchen-sink',
        version: '0.1.0',
        description: 'Fixture plugin exercising every component type',
        author: 'Bubstack',
        provides_hooks: ['pre_llm_call'],
      })
    })
  })

  describe('__init__.py', () => {
    const content = mustGet(byPath, '.hermes-plugin/__init__.py')

    it('has the marker as line 1', () => {
      expect(content.split('\n')[0]).toBe('# GENERATED by moe-mint — edit moe-mint.yaml instead')
    })

    it('has no leftover placeholders', () => {
      expect(content).not.toMatch(/__[A-Z_]+__/)
    })

    it('registers skills with Path(skill_md), not a bare string', () => {
      expect(content).toContain('Path(skill_md)')
    })

    it('carries the Path-not-str gotcha comment verbatim', () => {
      expect(content).toContain('register_skill requires a pathlib.Path — a str raises AttributeError and')
      expect(content).toContain('hermes silently disables the whole plugin (verified 2026-07-23).')
    })

    it('defines BOOTSTRAP_MARKER and gates injection on is_first_turn', () => {
      expect(content).toContain('BOOTSTRAP_MARKER = \'<plugin-bootstrap plugin="kitchen-sink">\'')
      expect(content).toContain('is_first_turn')
      expect(content).toContain('ctx.register_hook("pre_llm_call", pre_llm_call)')
    })

    it('resolves the bootstrap path to the skill SKILL.md in skill mode', () => {
      expect(content).toContain('"skills/using-kitchen-sink/SKILL.md".split("/")')
    })

    it('compiles cleanly with python3 -m py_compile', () => {
      expect(pyCompile(content).status).toBe(0)
    })
  })
})

describe('hermes adapter without commands/agents/hooks/mcp', () => {
  it('emits no warnings', () => {
    const dir = tmpFixture('name: plain\nversion: 1.0.0\ndescription: plain fixture\nbootstrap: none\n')
    const plainModel = buildModel(dir)
    const result = hermes.emit(plainModel)
    expect(result.warnings).toEqual([])
  })
})

describe('hermes adapter with bootstrap.generate', () => {
  it('resolves the bootstrap path to the generated bootstrap.md', () => {
    const dir = tmpFixture('name: gen-demo\nversion: 1.0.0\ndescription: generate-mode fixture\nbootstrap: generate\n')
    const genModel = buildModel(dir)
    const files = hermes.emit(genModel).files
    const py = files.find((f) => f.path === '.hermes-plugin/__init__.py')!.content
    const bootstrapParts = GENERATED_BOOTSTRAP_PATH.split('/')
      .map((p) => `"${p}"`)
      .join(', ')
    expect(py).toContain(`"${GENERATED_BOOTSTRAP_PATH}".split("/")`)
    expect(py).not.toMatch(/__[A-Z_]+__/)
    expect(pyCompile(py).status).toBe(0)
    // sanity: GENERATED_BOOTSTRAP_PATH really does have the shape we assume
    expect(bootstrapParts).toBeTruthy()

    const yamlContent = files.find((f) => f.path === '.hermes-plugin/plugin.yaml')!.content
    const rest = yamlContent.split('\n').slice(1).join('\n')
    expect(parse(rest)).toEqual({
      name: 'gen-demo',
      version: '1.0.0',
      description: 'generate-mode fixture',
      provides_hooks: ['pre_llm_call'],
    })
  })

  it('emits the generated bootstrap.md file itself, not just a reference to it', () => {
    const dir = tmpFixture('name: gen-demo\nversion: 1.0.0\ndescription: generate-mode fixture\nbootstrap: generate\n')
    const genModel = buildModel(dir)
    const bootstrapMd = hermes.emit(genModel).files.find((f) => f.path === GENERATED_BOOTSTRAP_PATH)
    expect(bootstrapMd?.content).toContain('# gen-demo plugin')
  })
})

describe('hermes adapter with bootstrap: none', () => {
  const dir = tmpFixture('name: none-demo\nversion: 1.0.0\ndescription: bootstrap-none fixture\nbootstrap: none\n')
  const noneModel = buildModel(dir)
  const files = hermes.emit(noneModel).files
  const py = files.find((f) => f.path === '.hermes-plugin/__init__.py')!.content
  const yamlContent = files.find((f) => f.path === '.hermes-plugin/plugin.yaml')!.content

  it('omits pre_llm_call, BOOTSTRAP_MARKER, and register_hook entirely', () => {
    expect(py).not.toMatch(/__[A-Z_]+__/)
    expect(py).not.toContain('pre_llm_call')
    expect(py).not.toContain('BOOTSTRAP_MARKER')
    expect(py).not.toContain('register_hook')
    expect(py).toContain('def register(ctx):')
    expect(py).toContain('Path(skill_md)')
  })

  it('compiles cleanly with python3 -m py_compile', () => {
    expect(pyCompile(py).status).toBe(0)
  })

  it('omits provides_hooks from plugin.yaml', () => {
    const rest = yamlContent.split('\n').slice(1).join('\n')
    const parsed = parse(rest) as Record<string, unknown>
    expect(parsed).not.toHaveProperty('provides_hooks')
    expect(parsed).toEqual({
      name: 'none-demo',
      version: '1.0.0',
      description: 'bootstrap-none fixture',
    })
  })
})

describe('hermes adapter installDoc', () => {
  it('includes a Caveats section', () => {
    const doc = hermes.installDoc?.(model)
    expect(doc).toContain('## Caveats')
  })

  it('covers the plugin.yaml/init.py warning caveat', () => {
    const doc = hermes.installDoc?.(model)
    expect(doc).toContain("doesn't contain plugin.yaml or __init__.py")
  })

  it('covers the hermes plugins enable name caveat', () => {
    const doc = hermes.installDoc?.(model)
    expect(doc).toContain('hermes plugins enable')
  })

  it('covers the __pycache__ litter caveat', () => {
    const doc = hermes.installDoc?.(model)
    expect(doc).toContain('__pycache__')
  })
})

describe('hermes plugin.py -- execution smoke test', () => {
  it('registers skills as Path instances and injects the bootstrap marker via the captured pre_llm_call hook', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-hermes-exec-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      'name: demo\nversion: 1.0.0\ndescription: exec fixture\nbootstrap:\n  skill: using-demo\n',
    )
    mkdirSync(join(dir, 'skills', 'using-demo'), { recursive: true })
    writeFileSync(
      join(dir, 'skills', 'using-demo', 'SKILL.md'),
      '---\nname: using-demo\ndescription: exec fixture skill\n---\n\n# Using Demo\n\nDemo skill body.\n',
    )

    const demoModel = buildModel(dir)
    const result = hermes.emit(demoModel)
    writeFileSet(dir, result.files)

    const initPath = join(dir, '.hermes-plugin', '__init__.py')
    const driverPath = join(dir, 'driver.py')
    writeFileSync(
      driverPath,
      [
        'import importlib.util',
        'import pathlib',
        'import sys',
        '',
        `spec = importlib.util.spec_from_file_location("plugin_mod", ${JSON.stringify(initPath)})`,
        'mod = importlib.util.module_from_spec(spec)',
        'spec.loader.exec_module(mod)',
        '',
        'calls = {"skills": [], "hooks": {}}',
        '',
        'class FakeCtx:',
        '    def register_skill(self, name, path):',
        '        calls["skills"].append((name, path))',
        '',
        '    def register_hook(self, name, fn):',
        '        calls["hooks"][name] = fn',
        '',
        'ctx = FakeCtx()',
        'mod.register(ctx)',
        '',
        'assert calls["skills"], "expected at least one registered skill"',
        'for name, path in calls["skills"]:',
        '    assert isinstance(path, pathlib.Path), f"{name} was registered with {type(path)}, not Path"',
        '',
        'hook = calls["hooks"]["pre_llm_call"]',
        'result = hook(is_first_turn=True)',
        'assert isinstance(result, dict), f"expected a dict, got {result!r}"',
        'assert \'<plugin-bootstrap plugin="demo">\' in result["context"]',
        'assert "Demo skill body." in result["context"]',
        '',
        'print("SMOKE_TEST_OK")',
        '',
      ].join('\n'),
    )

    const stdout = execFileSync('python3', [driverPath], { encoding: 'utf8' })
    expect(stdout).toContain('SMOKE_TEST_OK')
  })

  it('tolerates a missing bootstrap file: skills still register, no pre_llm_call hook, warns to stderr', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-hermes-exec-nobootstrap-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      'name: demo\nversion: 1.0.0\ndescription: missing-bootstrap fixture\nbootstrap: generate\n',
    )
    mkdirSync(join(dir, 'skills', 'a-skill'), { recursive: true })
    writeFileSync(
      join(dir, 'skills', 'a-skill', 'SKILL.md'),
      '---\nname: a-skill\ndescription: missing-bootstrap fixture skill\n---\n\n# A Skill\n\nSkill body.\n',
    )

    const demoModel = buildModel(dir)
    const result = hermes.emit(demoModel)
    writeFileSet(dir, result.files)

    // Delete the generated bootstrap file after writing the fileset, simulating
    // a broken/incomplete install where __init__.py exists but the bootstrap
    // content it reads at runtime does not.
    rmSync(join(dir, 'hooks', 'moe-mint', 'bootstrap.md'))

    const initPath = join(dir, '.hermes-plugin', '__init__.py')
    const driverPath = join(dir, 'driver.py')
    writeFileSync(
      driverPath,
      [
        'import importlib.util',
        'import pathlib',
        'import sys',
        '',
        `spec = importlib.util.spec_from_file_location("plugin_mod", ${JSON.stringify(initPath)})`,
        'mod = importlib.util.module_from_spec(spec)',
        'spec.loader.exec_module(mod)',
        '',
        'calls = {"skills": [], "hooks": {}}',
        '',
        'class FakeCtx:',
        '    def register_skill(self, name, path):',
        '        calls["skills"].append((name, path))',
        '',
        '    def register_hook(self, name, fn):',
        '        calls["hooks"][name] = fn',
        '',
        'ctx = FakeCtx()',
        'mod.register(ctx)  # must not raise despite the missing bootstrap file',
        '',
        'assert calls["skills"], "expected at least one registered skill"',
        'for name, path in calls["skills"]:',
        '    assert isinstance(path, pathlib.Path), f"{name} was registered with {type(path)}, not Path"',
        '',
        'assert "pre_llm_call" not in calls["hooks"], "no hook should be registered when bootstrap is unavailable"',
        '',
        'print("SMOKE_TEST_OK")',
        '',
      ].join('\n'),
    )

    const proc = spawnSync('python3', [driverPath], { encoding: 'utf8' })
    expect(proc.status).toBe(0)
    expect(proc.stdout).toContain('SMOKE_TEST_OK')
    expect(proc.stderr).toContain('demo plugin: bootstrap unavailable')
    expect(proc.stderr).toContain('skills registered without session bootstrap')
  })

  it('emits syntactically valid Python with multi-segment component paths (regression: path charset)', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-hermes-multipath-'))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      'name: multi-path\nversion: 1.0.0\ndescription: multi-segment component path fixture\nbootstrap:\n  skill: example\ncomponents:\n  skills: my/skills\n',
    )
    mkdirSync(join(dir, 'my', 'skills', 'example'), { recursive: true })
    writeFileSync(
      join(dir, 'my', 'skills', 'example', 'SKILL.md'),
      '---\nname: example\ndescription: skill in nested component path\n---\n\n# Example\n\nExample skill body.\n',
    )

    const mpModel = buildModel(dir)
    const result = hermes.emit(mpModel)
    const initPy = result.files.find((f) => f.path === '.hermes-plugin/__init__.py')!.content

    // Ensure no placeholders leaked through
    expect(initPy).not.toMatch(/__[A-Z_]+__/)

    // Ensure the emitted Python is syntactically valid (this catches quote/backslash injection attacks)
    expect(pyCompile(initPy).status).toBe(0)
  })
})
