import { describe, it, expect } from 'vitest'
import { byPathMap, mustGet, withV1Policy } from '../helpers.js'
import { mkdtempSync, mkdirSync, realpathSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { buildModel, type PluginModel } from '../../src/model.js'
import { adjustedModel, substituteAllSkills } from '../../src/vocabulary.js'
import { writeFileSet } from '../../src/fileset.js'
import { opencode } from '../../src/adapters/opencode.js'
import { adapters, getAdapter } from '../../src/adapters/index.js'
import { GENERATED_BOOTSTRAP_PATH } from '../../src/bootstrap/generated.js'

const model = buildModel('fixtures/kitchen-sink')

function emitOpenCode(sourceModel: PluginModel) {
  return opencode.emit(adjustedModel(sourceModel, opencode.skillLayout))
}

function tmpFixture(yaml: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'mint-opencode-'))
  writeFileSync(join(dir, 'moe-mint.yaml'), withV1Policy(yaml))
  return dir
}

describe('adapter registry', () => {
  it('registers opencode between kimi and pi', () => {
    const names = adapters.map((a) => a.name)
    expect(names).toContain('opencode')
    expect(getAdapter('opencode')).toBe(opencode)
    expect(names.indexOf('opencode')).toBe(names.indexOf('kimi') + 1)
    expect(names.indexOf('opencode')).toBe(names.indexOf('pi') - 1)
  })
})

describe('opencode adapter', () => {
  const result = emitOpenCode(model)
  const byPath = byPathMap(result.files)

  it('derives capabilities from emitted OpenCode projection files', () => {
    expect(result.emittedCapabilities).toEqual([
      'skill-discovery', 'command-discovery', 'agent-discovery', 'bootstrap-routing',
    ])
  })

  it('declares expected support levels', () => {
    expect(opencode.support).toEqual({
      skills: 'full',
      commands: 'full',
      agents: 'partial',
      hooks: 'none',
      mcp: 'none',
      bootstrap: 'full',
    })
  })

  it('keeps package.json out of adapter files and contributes only its server export', () => {
    expect(byPath['package.json']).toBeUndefined()
    expect(result.packageContribution).toEqual({
      owner: 'opencode',
      exports: { './server': './.opencode/plugins/kitchen-sink.js' },
    })
  })

  it('emits the plugin JS with no leftover placeholders, the marker guard string, and skills-dir registration', () => {
    const js = mustGet(byPath, '.opencode/plugins/kitchen-sink.js')
    expect(js).not.toMatch(/__[A-Z_]+__/)
    expect(js).toContain('<plugin-bootstrap plugin="kitchen-sink">')
    expect(js).toContain("path.resolve(__dirname, '../../.opencode/skills')")
    expect(js).toContain('config.skills.paths.push(skillsDir)')
    expect(js).toContain('export const KitchenSinkPlugin = async ({ client, directory }) => {')
    expect(js.split('\n')[1]).toBe('// GENERATED by moe-mint — edit moe-mint.yaml instead')
  })

  it('resolves the bootstrap path to the skill SKILL.md in skill mode', () => {
    const js = mustGet(byPath, '.opencode/plugins/kitchen-sink.js')
    expect(js).toContain("path.resolve(__dirname, '../../.opencode/skills/using-kitchen-sink/SKILL.md')")
  })

  it('emits ks-hello.md with the marker-as-YAML-comment, description frontmatter, and body verbatim', () => {
    expect(mustGet(byPath, '.opencode/command/ks-hello.md')).toBe(
      '---\n' +
        '# GENERATED by moe-mint — edit moe-mint.yaml instead\n' +
        'description: Say hello from the kitchen-sink fixture\n' +
        '---\n' +
        '\n' +
        'Say a cheerful hello to $ARGUMENTS (default: the current user).\n',
    )
  })

  it('emits ks-reviewer.md with description + mode: subagent frontmatter, body verbatim, tools dropped', () => {
    expect(mustGet(byPath, '.opencode/agent/ks-reviewer.md')).toBe(
      '---\n' +
        '# GENERATED by moe-mint — edit moe-mint.yaml instead\n' +
        'description: Reviews kitchen-sink output for fixture correctness\n' +
        'mode: subagent\n' +
        '---\n' +
        '\n' +
        'You review kitchen-sink fixture output. Report anything that looks broken.\n',
    )
    expect(mustGet(byPath, '.opencode/agent/ks-reviewer.md')).not.toContain('tools')
  })

  it('warns about hooks, mcp, and dropped agent tool restrictions', () => {
    expect(result.limitations.map((limitation) => limitation.message)).toEqual([
      'hooks are not emitted for opencode',
      'mcp servers are not emitted for opencode in v1',
      'agent tool restrictions are not translated for opencode',
    ])
  })
})

describe('opencode adapter with a plugin name starting with a digit', () => {
  it('prefixes the PascalCase export so it stays a valid JS identifier', async () => {
    const dir = tmpFixture('name: 123-tool\nversion: 1.0.0\ndescription: leading-digit name fixture\nbootstrap: none\n')
    const digitModel = buildModel(dir)
    const js = emitOpenCode(digitModel).files.find((f) => f.path === '.opencode/plugins/123-tool.js')!.content
    expect(js).toContain('export const _123ToolPlugin = async ({ client, directory }) => {')
    // Prove it's actually valid JS, not just string matching: execute it.
    mkdirSync(join(dir, '.opencode', 'plugins'), { recursive: true })
    const pluginAbsPath = join(dir, '.opencode', 'plugins', '123-tool.js')
    writeFileSync(pluginAbsPath, js)
    const mod = (await import(pathToFileURL(pluginAbsPath).href)) as Record<string, unknown>
    expect(typeof mod._123ToolPlugin).toBe('function')
  })
})

describe('opencode adapter without hooks/mcp/tools-bearing agents', () => {
  it('emits no warnings', () => {
    const dir = tmpFixture('name: plain\nversion: 1.0.0\ndescription: plain fixture\nbootstrap: none\n')
    const plainModel = buildModel(dir)
    const result = emitOpenCode(plainModel)
    expect(result.limitations).toEqual([])
  })
})

describe('opencode adapter with bootstrap.generate', () => {
  it('resolves the bootstrap path to the generated bootstrap.md', () => {
    const dir = tmpFixture('name: gen-demo\nversion: 1.0.0\ndescription: generate-mode fixture\nbootstrap: generate\n')
    const genModel = buildModel(dir)
    const js = emitOpenCode(genModel).files.find((f) => f.path === '.opencode/plugins/gen-demo.js')!.content
    expect(js).toContain(`path.resolve(__dirname, '../../${GENERATED_BOOTSTRAP_PATH}')`)
    expect(js).not.toMatch(/__[A-Z_]+__/)
  })

  it('emits the generated bootstrap.md file itself, not just a reference to it', () => {
    const dir = tmpFixture('name: gen-demo\nversion: 1.0.0\ndescription: generate-mode fixture\nbootstrap: generate\n')
    const genModel = buildModel(dir)
    const bootstrapMd = emitOpenCode(genModel).files.find((f) => f.path === GENERATED_BOOTSTRAP_PATH)
    expect(bootstrapMd?.content).toContain('# gen-demo plugin')
  })
})

describe('opencode adapter with bootstrap: none', () => {
  it('omits the bootstrap cache and message-transform hook, keeping only the config hook', () => {
    const dir = tmpFixture('name: none-demo\nversion: 1.0.0\ndescription: bootstrap-none fixture\nbootstrap: none\n')
    const noneModel = buildModel(dir)
    const js = emitOpenCode(noneModel).files.find((f) => f.path === '.opencode/plugins/none-demo.js')!.content
    expect(js).not.toContain('_bootstrapCache')
    expect(js).not.toContain('experimental.chat.messages.transform')
    expect(js).not.toContain('BOOTSTRAP_MARKER')
    expect(js).toContain('config.skills.paths.push(skillsDir)')
    expect(js).not.toMatch(/__[A-Z_]+__/)
  })
})

describe('opencode plugin JS — dynamic import execution (skill mode)', () => {
  it('registers the skills dir idempotently and injects the bootstrap exactly once across repeated transform calls', async () => {
    // realpath: the imported plugin resolves its own path through macOS's
    // /var -> /private/var symlink, so the expected paths must too.
    const dir = realpathSync(mkdtempSync(join(tmpdir(), 'mint-opencode-exec-')))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      withV1Policy('name: demo\nversion: 1.0.0\ndescription: exec fixture\nbootstrap:\n  skill: using-demo\n'),
    )
    mkdirSync(join(dir, 'skills', 'using-demo'), { recursive: true })
    writeFileSync(
      join(dir, 'skills', 'using-demo', 'SKILL.md'),
      '---\nname: using-demo\ndescription: exec fixture skill\n---\n\n# Using Demo\n\nDemo skill body.\n',
    )

    const demoModel = buildModel(dir)
    const result = emitOpenCode(demoModel)
    const renderedSkills = substituteAllSkills(
      dir,
      demoModel,
      { tokens: new Map(), blocks: new Map() },
      [opencode],
    )
    writeFileSet(dir, [...result.files, ...renderedSkills])

    const pluginAbsPath = join(dir, '.opencode', 'plugins', 'demo.js')
    const mod = (await import(pathToFileURL(pluginAbsPath).href)) as Record<string, unknown>
    const factory = mod.DemoPlugin as (opts: { client: null; directory: string }) => Promise<{
      config: (config: { skills?: { paths?: string[] } }) => Promise<void>
      'experimental.chat.messages.transform': (
        input: unknown,
        output: { messages: Array<{ info: { role: string }; parts: Array<{ type: string; text: string }> }> },
      ) => Promise<void>
    }>
    expect(typeof factory).toBe('function')

    const instance = await factory({ client: null, directory: '' })

    // config hook: idempotent across repeated calls.
    const config: { skills: { paths: string[] } } = { skills: { paths: [] } }
    await instance.config(config)
    await instance.config(config)
    expect(config.skills.paths).toEqual([join(dir, '.opencode/skills')])

    // transform hook: exactly one bootstrap part after two calls. The message
    // is held in its own binding rather than read back as output.messages[0]:
    // the emitted hook unshifts into `parts` in place, so this is the same
    // object the transform mutated, and an indexed read of a locally-built
    // array is `| undefined` under noUncheckedIndexedAccess.
    const message = { info: { role: 'user' }, parts: [{ type: 'text', text: 'hi' }] }
    const output = { messages: [message] }
    await instance['experimental.chat.messages.transform']({}, output)
    await instance['experimental.chat.messages.transform']({}, output)

    const bootstrapParts = message.parts.filter(
      (p) => p.type === 'text' && p.text.includes('<plugin-bootstrap plugin="demo">'),
    )
    expect(bootstrapParts).toHaveLength(1)
    expect(message.parts).toHaveLength(2)
    expect(bootstrapParts[0]?.text).toContain('Demo skill body.')
    expect(bootstrapParts[0]?.text).not.toContain('name: using-demo')
  })
})

describe('opencode plugin JS — dynamic import execution (bootstrap: none)', () => {
  it('exposes only the config hook', async () => {
    const dir = realpathSync(mkdtempSync(join(tmpdir(), 'mint-opencode-exec-none-')))
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      withV1Policy('name: nodemo\nversion: 1.0.0\ndescription: exec none fixture\nbootstrap: none\n'),
    )
    mkdirSync(join(dir, 'skills', 'demo'), { recursive: true })
    writeFileSync(join(dir, 'skills', 'demo', 'SKILL.md'), '---\nname: demo\ndescription: demo\n---\n\nBody.\n')

    const noneModel = buildModel(dir)
    const result = emitOpenCode(noneModel)
    writeFileSet(dir, result.files)

    const pluginAbsPath = join(dir, '.opencode', 'plugins', 'nodemo.js')
    const mod = (await import(pathToFileURL(pluginAbsPath).href)) as Record<string, unknown>
    const factory = mod.NodemoPlugin as (opts: { client: null; directory: string }) => Promise<Record<string, unknown>>
    const instance = await factory({ client: null, directory: '' })

    expect(instance['experimental.chat.messages.transform']).toBeUndefined()

    const config: { skills: { paths: string[] } } = { skills: { paths: [] } }
    await (instance.config as (c: typeof config) => Promise<void>)(config)
    expect(config.skills.paths).toEqual([join(dir, '.opencode/skills')])
  })
})
