import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { PluginModel } from './model.js'
import type { HarnessAdapter, SkillDelivery } from './adapters/types.js'
import type { FileSet, GeneratedFile } from './fileset.js'
import { renderMatrix } from './matrix.js'

const GENERATED_MARKER = '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->'

// Display names for docs/install/<name>.md headings and support-matrix.md
// prose. Deliberately hardcoded here rather than an adapter field (keeps
// HarnessAdapter minimal) — one more entry per adapter is a small, static
// cost the docs stage alone pays.
const DISPLAY_NAMES: Record<string, string> = {
  'claude-code': 'Claude Code',
  cursor: 'Cursor',
  codex: 'Codex',
  kimi: 'Kimi Code',
  opencode: 'OpenCode',
  pi: 'Pi',
  'agent-plugins-1.0': 'Agent Plugins 1.0 clients',
  copilot: 'GitHub Copilot CLI',
}

// Exported so README injection (below) can reuse the same names as the
// docs/install/<name>.md headings instead of maintaining a second map.
export function displayName(adapterName: string): string {
  return DISPLAY_NAMES[adapterName] ?? adapterName
}

function installDocFile(model: PluginModel, adapter: HarnessAdapter): GeneratedFile | undefined {
  if (!adapter.installDoc) return undefined
  const body = adapter.installDoc(model)
  const content =
    [
      GENERATED_MARKER,
      '',
      `# Installing ${model.config.name} on ${displayName(adapter.name)}`,
      '',
      body,
    ].join('\n') + '\n'
  return { path: `docs/install/${adapter.name}.md`, content }
}

// support-matrix.md's Notes section calls out three things that a plain
// support-level table can't: Copilot consumes the Claude Code layout rather
// than its own files, and the CRLF/.gitattributes caveat applies to anyone
// consuming the emitted shell hooks (Design decision 2).
function notes(model: PluginModel): string[] {
  let bootstrap: string
  if (model.config.bootstrap.kind === 'none') {
    bootstrap = '- This plugin configures no bootstrap content; no adapter injects or activates one.'
  } else if (model.config.bootstrap.kind === 'skill') {
    bootstrap =
      "- This plugin's named bootstrap skill is actively injected at session start by Claude Code, Cursor, OpenCode, and Pi; Kimi activates the named bootstrap skill, and Copilot consumes Claude Code's injection hook."
  } else {
    bootstrap =
      "- This plugin's generated bootstrap is actively injected at session start by Claude Code, Cursor, OpenCode, and Pi; Kimi cannot activate generated bootstrap content, and Copilot consumes Claude Code's injection hook."
  }

  return [
    '- Copilot consumes the Claude Code layout through `.claude-plugin/marketplace.json`; keep the `claude-code` adapter enabled when targeting Copilot.',
    bootstrap,
    model.config.bootstrap.kind === 'none'
      ? '- Codex still provides native skill discovery, without active bootstrap injection.'
      : '- Codex provides native skill discovery only; it has no active bootstrap injection.',
    '- Agent Plugins 1.0 provides skill discovery but no bootstrap mechanism.',
    '- Repos consuming shell-hook output should add `hooks/moe-mint/* text eol=lf` and `.cursor-plugin/hooks/moe-mint/* text eol=lf` to .gitattributes or accept drift warnings on autocrlf checkouts.',
  ]
}

function supportMatrixFile(
  model: PluginModel,
  achievedDelivery?: Record<string, SkillDelivery>,
): GeneratedFile {
  const content =
    [
      GENERATED_MARKER,
      '',
      `# ${model.config.name} harness support matrix`,
      '',
      renderMatrix(achievedDelivery).trimEnd(),
      '',
      '## Notes',
      '',
      ...notes(model),
    ].join('\n') + '\n'
  return { path: 'docs/support-matrix.md', content }
}

// Generates docs/install/<adapter-name>.md for each active adapter that
// implements installDoc, plus docs/support-matrix.md (always, independent of
// which adapters are active — it documents the tool's full registry, same
// as `moe-mint matrix`). Called by generate() after adapter emission;
// the returned files go through the same collision/manifest path as any
// adapter's output.
export function emitDocs(
  model: PluginModel,
  activeAdapters: HarnessAdapter[],
  achievedDelivery?: Record<string, SkillDelivery>,
): FileSet {
  const files: FileSet = []
  for (const adapter of activeAdapters) {
    const file = installDocFile(model, adapter)
    if (file) files.push(file)
  }
  files.push(supportMatrixFile(model, achievedDelivery))
  return files
}

const README_START = '<!-- moe-mint:install:start -->'
const README_END = '<!-- moe-mint:install:end -->'

function installMatrixTable(activeAdapters: HarnessAdapter[]): string {
  const rows = activeAdapters
    .filter((a) => a.installDoc)
    .map((a) => `| ${displayName(a.name)} | see docs/install/${a.name}.md |`)
  return ['| Harness | Install |', '|---|---|', ...rows].join('\n')
}

// Injects the install matrix into the plugin's README.md, between two
// hand-placed markers. README.md is a user file — never created, never
// manifest-tracked, never touched by validate — so this runs outside the
// FileSet/manifest machinery generate() uses for everything else. No
// README.md at all is silent (nothing to inject into, nothing written, no
// warning) since most component-only plugins won't have one; a README.md
// that exists but lacks either marker (or has them in the wrong order) DOES
// warn — that's a plugin author who has a README but hasn't opted into
// install-matrix injection yet, worth flagging.
export function injectReadme(
  root: string,
  activeAdapters: HarnessAdapter[],
): { injected: boolean; warning?: string } {
  const path = join(root, 'README.md')
  if (!existsSync(path)) return { injected: false }

  const content = readFileSync(path, 'utf8')
  const startIdx = content.indexOf(README_START)
  const endIdx = content.indexOf(README_END)
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    return {
      injected: false,
      warning: `README.md has no moe-mint install markers; skipping install-matrix injection\n  add ${README_START} and ${README_END} where the table should go`,
    }
  }

  const before = content.slice(0, startIdx + README_START.length)
  const after = content.slice(endIdx)
  const next = `${before}\n\n${installMatrixTable(activeAdapters)}\n\n${after}`

  if (next === content) return { injected: false }
  writeFileSync(path, next)
  return { injected: true }
}
