import type { PluginModel } from './model.js'
import type { HarnessAdapter } from './adapters/types.js'
import type { AdapterEmission } from './adapters/types.js'
import type { FileSet, GeneratedFile } from './fileset.js'
import { renderMatrix } from './matrix.js'
import type { TargetId } from './vocabulary.js'

const GENERATED_MARKER = '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->'

// Display names for docs/install/<name>.md headings and support-matrix.md
// prose. Deliberately hardcoded here rather than an adapter field (keeps
// HarnessAdapter minimal) — one more entry per adapter is a small, static
// cost the docs stage alone pays.
const DISPLAY_NAMES: Record<string, string> = {
  'claude-code': 'Claude Code',
  cursor: 'Cursor',
  codex: 'Codex',
  kimi: 'Kimi Code',
  opencode: 'OpenCode',
  pi: 'Pi',
  'agent-plugins-1.0': 'Agent Plugins 1.0 clients',
  copilot: 'GitHub Copilot CLI',
}

export function displayName(adapterName: string): string {
  return DISPLAY_NAMES[adapterName] ?? adapterName
}

function installDocFile(model: PluginModel, adapter: HarnessAdapter): GeneratedFile | undefined {
  if (!adapter.installDoc) return undefined
  const body = adapter.installDoc(model)
  const content =
    [
      GENERATED_MARKER,
      '',
      `# Installing ${model.config.name} on ${displayName(adapter.name)}`,
      '',
      body.trimEnd(),
    ].join('\n') + '\n'
  return { path: `docs/install/${adapter.name}.md`, content }
}

// support-matrix.md's Notes section calls out details a capability table cannot:
// Copilot consumes the Claude Code layout rather
// than its own files, and the CRLF/.gitattributes caveat applies to anyone
// consuming the emitted shell hooks (Design decision 2).
const NOTES = [
  '- Copilot consumes the Claude Code layout through `.claude-plugin/marketplace.json`; keep the `claude-code` adapter enabled when targeting Copilot.',
  '- Repos consuming shell-hook output should add `hooks/moe-mint/* text eol=lf` to .gitattributes or accept drift warnings on autocrlf checkouts.',
]

function supportMatrixFile(model: PluginModel, emissions?: Partial<Record<TargetId, AdapterEmission>>): GeneratedFile {
  const content =
    [
      GENERATED_MARKER,
      '',
      `# ${model.config.name} harness support matrix`,
      '',
      renderMatrix(emissions).trimEnd(),
      '',
      '## Notes',
      '',
      ...NOTES,
    ].join('\n') + '\n'
  return { path: 'docs/support-matrix.md', content }
}

// Generates docs/install/<adapter-name>.md for each active adapter that
// implements installDoc, plus docs/support-matrix.md (always, independent of
// which adapters are active — it documents the tool's full registry, same
// as `moe-mint matrix`). Called by generate() after adapter emission;
// the returned files go through the same collision/manifest path as any
// adapter's output.
export function emitDocs(
  model: PluginModel,
  activeAdapters: readonly HarnessAdapter[],
  emissions?: Partial<Record<TargetId, AdapterEmission>>,
): FileSet {
  const files: FileSet = []
  for (const adapter of activeAdapters) {
    const file = installDocFile(model, adapter)
    if (file) files.push(file)
  }
  files.push(supportMatrixFile(model, emissions))
  return files
}
