// moe-memory plugin for OpenCode — registers the skills directory and injects bootstrap context into the first user message.
// GENERATED by moe-mint — edit moe-mint.yaml instead

import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Minimal frontmatter stripper (dependency-free rather than pulling in a
// markdown/frontmatter package for a single bootstrap-file read).
const extractAndStripFrontmatter = (content) => {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!match) return { frontmatter: {}, content }
  const frontmatterStr = match[1]
  const body = match[2]
  const frontmatter = {}
  for (const line of frontmatterStr.split('\n')) {
    const colonIdx = line.indexOf(':')
    if (colonIdx > 0) {
      const key = line.slice(0, colonIdx).trim()
      const value = line.slice(colonIdx + 1).trim().replace(/^["']|["']$/g, '')
      frontmatter[key] = value
    }
  }
  return { frontmatter, content: body }
}

const skillsDir = path.resolve(__dirname, '../../.opencode/skills')
const BOOTSTRAP_MARKER = '<plugin-bootstrap plugin="moe-memory">'

// Module-level cache for bootstrap content. The bootstrap file does not
// change during a session, so reading and parsing it once eliminates
// redundant fs work on every agent step.
let _bootstrapCache = undefined // undefined = not yet loaded, null = file missing

export const MoeMemoryPlugin = async ({ client, directory }) => {
  const getBootstrapContent = () => {
    if (_bootstrapCache !== undefined) return _bootstrapCache

    const bootstrapPath = path.resolve(__dirname, '../../.opencode/skills/remembering-conversations/SKILL.md')
    if (!fs.existsSync(bootstrapPath)) {
      _bootstrapCache = null
      return null
    }

    const fullContent = fs.readFileSync(bootstrapPath, 'utf8')
    const { content } = extractAndStripFrontmatter(fullContent)

    _bootstrapCache = BOOTSTRAP_MARKER + '\n' + content + '\n</plugin-bootstrap>'
    return _bootstrapCache
  }

  return {
    // Inject the plugin's skills path into live config so OpenCode discovers
    // its skills without requiring manual symlinks or config file edits.
    config: async (config) => {
      config.skills = config.skills || {}
      config.skills.paths = config.skills.paths || []
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir)
      }
    },

    // Inject bootstrap into the first user message of each session, guarded
    // by a marker substring so re-running the transform on an already
    // transformed message array never injects twice.
    'experimental.chat.messages.transform': async (_input, output) => {
      const bootstrap = getBootstrapContent()
      if (!bootstrap || !output.messages.length) return
      const firstUser = output.messages.find((m) => m.info.role === 'user')
      if (!firstUser || !firstUser.parts.length) return

      if (firstUser.parts.some((p) => p.type === 'text' && p.text.includes(BOOTSTRAP_MARKER))) return

      const ref = firstUser.parts[0]
      firstUser.parts.unshift({ ...ref, type: 'text', text: bootstrap })
    },
  }
}
