// moe-backstory extension for Pi — registers the skills directory.
// GENERATED by moe-mint — edit moe-mint.yaml instead

import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent'

const extensionDir = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(extensionDir, '../..')
const skillsDir = resolve(packageRoot, 'skills')

export default function extension(pi: ExtensionAPI) {
  pi.on('resources_discover', async () => ({
    skillPaths: [skillsDir],
  }))
}
