import type { PluginModel } from '../model.js'

// Repo-relative path of the bootstrap markdown file emitted in
// bootstrap.generate mode. Shared by every adapter that consumes it
// (claude-code/cursor cat it via sessionStartScript; opencode/pi
// read it at runtime) so the path lives in exactly one place.
export const GENERATED_BOOTSTRAP_PATH = 'hooks/moe-mint/bootstrap.md'

// Synthesizes a minimal bootstrap markdown file for bootstrap.generate mode:
// a heading naming the plugin, one instruction line, and a bullet per skill
// (in model.skills order) pointing the harness at when to invoke it. This is
// the generate-mode substitute for a hand-authored bootstrap skill's
// SKILL.md.
export function generatedBootstrap(model: PluginModel): string {
  const lines = [
    '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->',
    `# ${model.config.name} plugin`,
    '',
    'Invoke the relevant skill BEFORE acting when a task matches its description.',
    '',
    ...model.skills.map((skill) => `- **${skill.name}**: ${skill.description}`),
  ]
  return lines.join('\n') + '\n'
}
