// Bash/cmd bootstrap-hook templates for harnesses (currently claude-code and
// cursor) that support a SessionStart hook. The session-start script loads
// the bootstrap content (a bootstrap skill's SKILL.md in skill mode, or the
// generated hooks/moe-mint/bootstrap.md in generate mode) into the
// session context; run-hook.cmd is a cmd/bash polyglot wrapper so the same
// hook works on Windows and Unix.
//
// Templates are plain string constants (not TS template literals) so bash's
// own ${...} syntax never collides with TS interpolation; placeholders are
// substituted with .replaceAll.

const SESSION_START_TEMPLATE =
  "#!/usr/bin/env bash\n# GENERATED by moe-mint — edit moe-mint.yaml instead\n# SessionStart bootstrap hook for the __PLUGIN_NAME__ plugin (emitted by moe-mint)\n\nset -euo pipefail\n\nSCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\nPLUGIN_ROOT=\"$(cd \"${SCRIPT_DIR}/__PLUGIN_ROOT_RELATIVE__\" && pwd)\"\n\nbootstrap_content=$(cat \"${PLUGIN_ROOT}/__BOOTSTRAP_PATH__\" 2>&1 || echo \"Error reading bootstrap skill\")\n\nescape_for_json() {\n    local s=\"$1\"\n    s=\"${s//\\\\/\\\\\\\\}\"\n    s=\"${s//\\\"/\\\\\\\"}\"\n    s=\"${s//$'\\n'/\\\\n}\"\n    s=\"${s//$'\\r'/\\\\r}\"\n    s=\"${s//$'\\t'/\\\\t}\"\n    printf '%s' \"$s\"\n}\n\nbootstrap_escaped=$(escape_for_json \"$bootstrap_content\")\nsession_context=\"<plugin-bootstrap plugin=\\\\\\\"__PLUGIN_NAME__\\\\\\\">\\nThe following skill from the __PLUGIN_NAME__ plugin is loaded at session start:\\n\\n${bootstrap_escaped}\\n</plugin-bootstrap>\"\n\nif [ -n \"${CURSOR_PLUGIN_ROOT:-}\" ]; then\n  printf '{\\n  \"additional_context\": \"%s\"\\n}\\n' \"$session_context\" | cat\nelif [ -n \"${CLAUDE_PLUGIN_ROOT:-}\" ] && [ -z \"${COPILOT_CLI:-}\" ]; then\n  printf '{\\n  \"hookSpecificOutput\": {\\n    \"hookEventName\": \"SessionStart\",\\n    \"additionalContext\": \"%s\"\\n  }\\n}\\n' \"$session_context\" | cat\nelse\n  printf '{\\n  \"additionalContext\": \"%s\"\\n}\\n' \"$session_context\" | cat\nfi\n\nexit 0\n"

const RUN_HOOK_CMD_TEMPLATE =
  ": << 'CMDBLOCK'\n@echo off\nREM GENERATED by moe-mint -- edit moe-mint.yaml instead\nREM Cross-platform polyglot wrapper for hook scripts.\nREM On Windows: cmd.exe runs the batch portion, which finds and calls bash.\nREM On Unix: the shell interprets this as a script (: is a no-op in bash).\nREM Usage: run-hook.cmd <script-name> [args...]\n\nif \"%~1\"==\"\" (\n    echo run-hook.cmd: missing script name >&2\n    exit /b 1\n)\n\nset \"HOOK_DIR=%~dp0\"\n\nif exist \"C:\\Program Files\\Git\\bin\\bash.exe\" (\n    \"C:\\Program Files\\Git\\bin\\bash.exe\" \"%HOOK_DIR%%~1\" %2 %3 %4 %5 %6 %7 %8 %9\n    exit /b %ERRORLEVEL%\n)\nif exist \"C:\\Program Files (x86)\\Git\\bin\\bash.exe\" (\n    \"C:\\Program Files (x86)\\Git\\bin\\bash.exe\" \"%HOOK_DIR%%~1\" %2 %3 %4 %5 %6 %7 %8 %9\n    exit /b %ERRORLEVEL%\n)\n\nwhere bash >nul 2>nul\nif %ERRORLEVEL% equ 0 (\n    bash \"%HOOK_DIR%%~1\" %2 %3 %4 %5 %6 %7 %8 %9\n    exit /b %ERRORLEVEL%\n)\n\nREM No bash found. Say so, then exit 0 anyway. This wrapper dispatches the\nREM SessionStart hook that bootstraps the plugin, so a silent skip here means\nREM the plugin is simply off with nothing anywhere saying why. Still exit 0: a\nREM non-zero SessionStart hook can break every session on the machine.\necho run-hook.cmd: no bash found, so hook \"%~1\" did NOT run. >&2\necho   This plugin's hooks are shell scripts and need a bash on this machine. >&2\necho   Install Git for Windows, or use WSL2. >&2\nexit /b 0\nCMDBLOCK\n\n# Unix: run the named script directly\nSCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\nSCRIPT_NAME=\"$1\"\nshift\nexec bash \"${SCRIPT_DIR}/${SCRIPT_NAME}\" \"$@\"\n"

export function sessionStartScript(opts: {
  pluginName: string
  bootstrapContentPath: string
  pluginRootRelative?: string
}): string {
  return SESSION_START_TEMPLATE.replaceAll('__PLUGIN_NAME__', opts.pluginName)
    .replaceAll('__PLUGIN_ROOT_RELATIVE__', opts.pluginRootRelative ?? '../..')
    .replaceAll('__BOOTSTRAP_PATH__', opts.bootstrapContentPath)
}

export function runHookCmd(): string {
  return RUN_HOOK_CMD_TEMPLATE
}

// Shared by the claude-code adapter (mergedClaudeHooks) and tests, so the
// SessionStart entry the adapter appends is defined in exactly one place.
export const BOOTSTRAP_HOOK_ENTRY = {
  matcher: 'startup|clear|compact',
  hooks: [
    {
      type: 'command',
      command: '"${CLAUDE_PLUGIN_ROOT}/hooks/moe-mint/run-hook.cmd" session-start',
      shell: 'bash',
      async: false,
    },
  ],
}

interface ClaudeHooksDoc {
  hooks?: Record<string, unknown[]>
  [key: string]: unknown
}

// Deep-clones userHooks (or starts fresh from {hooks:{}} when undefined) and
// appends BOOTSTRAP_HOOK_ENTRY to hooks.SessionStart, creating the array if
// needed. Never mutates the input.
export function mergedClaudeHooks(userHooks: unknown): unknown {
  const merged = (userHooks === undefined ? { hooks: {} } : structuredClone(userHooks)) as ClaudeHooksDoc
  const hooks = merged.hooks ?? (merged.hooks = {})
  const sessionStart = Array.isArray(hooks.SessionStart) ? hooks.SessionStart : (hooks.SessionStart = [])
  sessionStart.push(BOOTSTRAP_HOOK_ENTRY)
  return merged
}
