import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync, chmodSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { sessionStartScript, runHookCmd, mergedClaudeHooks } from '../src/bootstrap/shell-hook.js'

describe('sessionStartScript', () => {
  const script = sessionStartScript({ pluginName: 'demo', bootstrapContentPath: 'skills/using-demo/SKILL.md' })

  it('starts with shebang then GENERATED marker', () => {
    const lines = script.split('\n')
    expect(lines[0]).toBe('#!/usr/bin/env bash')
    expect(lines[1]).toMatch(/^# GENERATED by moe-mint/)
  })

  it('substitutes plugin name and skill dir with no leftover placeholders', () => {
    // Triple backslash: session_context is a bash-double-quoted string whose
    // value is later spliced verbatim (via printf %s) into a JSON string, so
    // the attribute quotes need both a bash-level escape (\\ -> \) and a
    // JSON-level escape (\" -> ") to survive as a valid \" in the JSON output.
    expect(script).toContain('plugin-bootstrap plugin=\\\\\\"demo\\\\\\"')
    expect(script).toContain('skills/using-demo/SKILL.md')
    expect(script).not.toMatch(/__[A-Z_]+__/)
  })

  it('emits valid JSON in all three harness formats when actually executed', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-boot-'))
    mkdirSync(join(dir, 'skills/using-demo'), { recursive: true })
    writeFileSync(join(dir, 'skills/using-demo/SKILL.md'), '---\nname: using-demo\n---\nLine "one"\n\ttabbed\n')
    mkdirSync(join(dir, 'hooks/moe-mint'), { recursive: true })
    const scriptPath = join(dir, 'hooks/moe-mint/session-start')
    writeFileSync(scriptPath, script)
    chmodSync(scriptPath, 0o755)
    const run = (env: Record<string, string>) =>
      JSON.parse(execFileSync('bash', [scriptPath], { env: { ...process.env, CURSOR_PLUGIN_ROOT: '', CLAUDE_PLUGIN_ROOT: '', COPILOT_CLI: '', ...env } }).toString())
    const claude = run({ CLAUDE_PLUGIN_ROOT: dir })
    expect(claude.hookSpecificOutput.hookEventName).toBe('SessionStart')
    expect(claude.hookSpecificOutput.additionalContext).toContain('Line \"one\"'.replace('\\"', '"'))
    const cursor = run({ CURSOR_PLUGIN_ROOT: dir })
    expect(cursor.additional_context).toContain('tabbed')
    const copilot = run({ CLAUDE_PLUGIN_ROOT: dir, COPILOT_CLI: '1' })
    expect(copilot.additionalContext).toContain('using-demo')
  })

  it('loads an adapter-private rendered bootstrap path from the plugin root', () => {
    const privateTreeScript = sessionStartScript({
      pluginName: 'demo',
      bootstrapContentPath: '.cursor-plugin/skills/using-demo/SKILL.md',
    })
    expect(privateTreeScript).toContain(
      '${PLUGIN_ROOT}/.cursor-plugin/skills/using-demo/SKILL.md',
    )
  })
})

describe('runHookCmd', () => {
  it('is a polyglot with the CMDBLOCK guard and unix exec tail', () => {
    const cmd = runHookCmd()
    expect(cmd.startsWith(": << 'CMDBLOCK'")).toBe(true)
    expect(cmd).toContain('exec bash "${SCRIPT_DIR}/${SCRIPT_NAME}"')
    expect(cmd).not.toContain('\r')
  })
})

describe('mergedClaudeHooks', () => {
  it('appends the bootstrap entry to existing SessionStart hooks', () => {
    const user = { hooks: { SessionStart: [{ matcher: 'startup', hooks: [{ type: 'command', command: 'echo hi' }] }] } }
    const merged = mergedClaudeHooks(user) as { hooks: { SessionStart: unknown[] } }
    expect(merged.hooks.SessionStart).toHaveLength(2)
    expect(JSON.stringify(merged.hooks.SessionStart[1])).toContain('hooks/moe-mint/run-hook.cmd')
    expect((user.hooks.SessionStart)).toHaveLength(1) // input not mutated
  })
  it('creates the structure when user has no hooks', () => {
    const merged = mergedClaudeHooks(undefined) as { hooks: { SessionStart: unknown[] } }
    expect(merged.hooks.SessionStart).toHaveLength(1)
  })
})
