import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildModel } from '../src/model.js'
import { generatedBootstrap } from '../src/bootstrap/generated.js'
import { writeFileSet } from '../src/fileset.js'
import { claudeCode } from '../src/adapters/claude-code.js'

describe('generatedBootstrap', () => {
  it('produces the exact marker/heading/instruction/bullet-list content for kitchen-sink', () => {
    const model = buildModel('fixtures/kitchen-sink')
    expect(generatedBootstrap(model)).toBe(
      [
        '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->',
        '# kitchen-sink plugin',
        '',
        'Invoke the relevant skill BEFORE acting when a task matches its description.',
        '',
        "- **greeting**: Use when the user asks for a greeting - produces a friendly greeting",
        "- **using-kitchen-sink**: Use when starting any conversation - explains the kitchen-sink fixture plugin's capabilities",
        '',
      ].join('\n'),
    )
  })
})

describe('bootstrap.generate mode, executed end-to-end', () => {
  it('claude-code session-start hook cats the generated bootstrap.md and surfaces its bullets in additionalContext', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mint-generate-e2e-'))
    mkdirSync(join(dir, 'skills', 'alpha'), { recursive: true })
    writeFileSync(join(dir, 'skills', 'alpha', 'SKILL.md'), '---\nname: alpha\ndescription: Handles alpha tasks\n---\n\nBody.\n')
    mkdirSync(join(dir, 'skills', 'beta'), { recursive: true })
    writeFileSync(join(dir, 'skills', 'beta', 'SKILL.md'), '---\nname: beta\ndescription: Handles beta tasks\n---\n\nBody.\n')
    writeFileSync(
      join(dir, 'moe-mint.yaml'),
      'name: generate-e2e\nversion: 1.0.0\ndescription: generate-mode end-to-end fixture\nbootstrap: generate\n',
    )

    const model = buildModel(dir)
    const result = claudeCode.emit(model)
    writeFileSet(dir, result.files)

    const scriptPath = join(dir, 'hooks/moe-mint/session-start')
    const output = JSON.parse(
      execFileSync('bash', [scriptPath], {
        env: { ...process.env, CLAUDE_PLUGIN_ROOT: dir, CURSOR_PLUGIN_ROOT: '', COPILOT_CLI: '' },
      }).toString(),
    )
    const additionalContext = output.hookSpecificOutput.additionalContext as string
    expect(additionalContext).toContain('- **alpha**: Handles alpha tasks')
    expect(additionalContext).toContain('- **beta**: Handles beta tasks')
    expect(additionalContext).toContain('Invoke the relevant skill BEFORE acting')
  })
})
