import { describe, it, expect } from 'vitest'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildModel } from '../src/model.js'
import { emitDocs } from '../src/docs-emit.js'
import { adapters } from '../src/adapters/index.js'
import { claudeCode } from '../src/adapters/claude-code.js'
import { opencode } from '../src/adapters/opencode.js'
import { pi } from '../src/adapters/pi.js'
import { agentPlugins } from '../src/adapters/agent-plugins.js'
import { kimi } from '../src/adapters/kimi.js'
import { opencodePluginPath } from '../src/bootstrap/node-package.js'
import type { HarnessAdapter } from '../src/adapters/types.js'
import { withV1Policy } from './helpers.js'

const model = buildModel('fixtures/kitchen-sink')

function tmpFixture(yaml: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'mint-docs-emit-'))
  writeFileSync(join(dir, 'moe-mint.yaml'), withV1Policy(yaml))
  return dir
}

const _fullSupport = {
  skills: 'full',
  commands: 'full',
  agents: 'full',
  hooks: 'full',
  mcp: 'full',
  bootstrap: 'full',
  rules: 'none',
  variables: 'none',
} as const


function adapterWithInstallDoc(name: string, body: string): HarnessAdapter {
  return {
    name,
    emit: () => ({ files: [], limitations: [], emittedCapabilities: [] }),
    installDoc: () => body,
  }
}

function adapterWithoutInstallDoc(name: string): HarnessAdapter {
  return { name, emit: () => ({ files: [], limitations: [], emittedCapabilities: [] }) }
}

describe('emitDocs install-doc files', () => {
  it('emits docs/install/<name>.md only for adapters implementing installDoc', () => {
    const withDoc = adapterWithInstallDoc('kimi', 'Body text for kimi.')
    const withoutDoc = adapterWithoutInstallDoc('codex')
    const files = emitDocs(model, [withDoc, withoutDoc])
    expect(files.some((f) => f.path === 'docs/install/kimi.md')).toBe(true)
    expect(files.some((f) => f.path === 'docs/install/codex.md')).toBe(false)
  })

  it('wraps the installDoc body with a generated marker and a heading naming the plugin and the mapped display name', () => {
    const withDoc = adapterWithInstallDoc('kimi', 'Body text for kimi.\n\n')
    const files = emitDocs(model, [withDoc])
    const file = files.find((f) => f.path === 'docs/install/kimi.md')!
    const lines = file.content.split('\n')
    expect(lines[0]).toBe('<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->')
    expect(lines[1]).toBe('')
    expect(lines[2]).toBe('# Installing kitchen-sink on Kimi Code')
    expect(lines[3]).toBe('')
    expect(file.content).toContain('Body text for kimi.')
    expect(file.content.endsWith('\n')).toBe(true)
    expect(file.content.endsWith('\n\n')).toBe(false)
  })

  it('falls back to the adapter name itself when it has no entry in the display-name map', () => {
    const withDoc = adapterWithInstallDoc('totally-unmapped-adapter', 'Body.')
    const files = emitDocs(model, [withDoc])
    const file = files.find((f) => f.path === 'docs/install/totally-unmapped-adapter.md')!
    expect(file.content).toContain('# Installing kitchen-sink on totally-unmapped-adapter')
  })

  it('emits no install-doc files at all when no active adapter implements installDoc', () => {
    const files = emitDocs(model, [adapterWithoutInstallDoc('codex'), adapterWithoutInstallDoc('cursor')])
    expect(files.some((f) => f.path.startsWith('docs/install/'))).toBe(false)
  })
})

describe('emitDocs support-matrix.md', () => {
  it('is always emitted, independent of the active adapter list', () => {
    const files = emitDocs(model, [])
    const file = files.find((f) => f.path === 'docs/support-matrix.md')
    expect(file).toBeDefined()
  })

  it('starts with the generated marker and a heading naming the plugin', () => {
    const files = emitDocs(model, [])
    const content = files.find((f) => f.path === 'docs/support-matrix.md')!.content
    const lines = content.split('\n')
    expect(lines[0]).toBe('<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->')
    expect(lines[1]).toBe('')
    expect(lines[2]).toBe('# kitchen-sink harness support matrix')
  })

  it('has exact content for the full 8-adapter registry: all rows plus the Notes section', () => {
    const content = emitDocs(model, adapters).find((f) => f.path === 'docs/support-matrix.md')!.content
    expect(content).toBe(
      [
        '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->',
        '',
        '# kitchen-sink harness support matrix',
        '',
        '| Harness | Emitted capabilities |',
        '|---|---|',
        '| claude-code | generate a plugin to inspect |',
        '| cursor | generate a plugin to inspect |',
        '| codex | generate a plugin to inspect |',
        '| kimi | generate a plugin to inspect |',
        '| opencode | generate a plugin to inspect |',
        '| pi | generate a plugin to inspect |',
        '| agent-plugins-1.0 | generate a plugin to inspect |',
        '| copilot | generate a plugin to inspect |',
        '',
        '## Notes',
        '',
        '- Copilot consumes the Claude Code layout through `.claude-plugin/marketplace.json`; keep the `claude-code` adapter enabled when targeting Copilot.',
        '- Repos consuming shell-hook output should add `hooks/moe-mint/* text eol=lf` to .gitattributes or accept drift warnings on autocrlf checkouts.',
        '',
      ].join('\n'),
    )
  })
})

describe('emitDocs with the real claude-code adapter (proves the pipe end to end)', () => {
  it('emits docs/install/claude-code.md with the marker, heading, and installDoc body', () => {
    const files = emitDocs(model, [claudeCode])
    const file = files.find((f) => f.path === 'docs/install/claude-code.md')!
    expect(file.content).toBe(
      [
        '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->',
        '',
        '# Installing kitchen-sink on Claude Code',
        '',
        claudeCode.installDoc!(model),
        '',
      ].join('\n'),
    )
  })

  it('emits one docs/install/<name>.md per adapter for the real 8-adapter registry (every adapter implements installDoc)', () => {
    const files = emitDocs(model, adapters)
    const installDocPaths = files.filter((f) => f.path.startsWith('docs/install/')).map((f) => f.path)
    expect(installDocPaths.sort()).toEqual(
      adapters.map((a) => `docs/install/${a.name}.md`).sort(),
    )
  })
})

describe('emitDocs install-doc files for the full 8-adapter registry (Task 2)', () => {
  it('emits docs/install/<name>.md for every adapter, each starting with the marker line and containing the plugin-and-harness heading', () => {
    const files = emitDocs(model, adapters)
    for (const adapter of adapters) {
      const file = files.find((f) => f.path === `docs/install/${adapter.name}.md`)
      expect(file, `missing docs/install/${adapter.name}.md`).toBeDefined()
      const lines = file!.content.split('\n')
      expect(lines[0]).toBe('<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->')
      expect(file!.content).toContain('# Installing kitchen-sink on ')
    }
  })
})

describe('opencode installDoc (exact content, kitchen-sink model)', () => {
  it('matches the computed body exactly', () => {
    const files = emitDocs(model, [opencode])
    const file = files.find((f) => f.path === 'docs/install/opencode.md')!
    const pluginPath = opencodePluginPath('kitchen-sink')
    expect(file.content).toBe(
      [
        '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->',
        '',
        '# Installing kitchen-sink on OpenCode',
        '',
        '## What gets emitted',
        '',
        "- a `./server` export contribution for the artifact's composed root `package.json`",
        `- \`${pluginPath}\`, the OpenCode plugin module that registers the plugin's skills directory and injects bootstrap context`,
        '- a `.opencode/command/<name>.md` file for each command (`ks-hello`)',
        '- a `.opencode/agent/<name>.md` file for each agent (`ks-reviewer`)',
        '',
        '## Installing',
        '',
        "Add the plugin to your project's `opencode.json`:",
        '',
        '```json',
        '{ "plugin": ["kitchen-sink@git+https://github.com/example/kitchen-sink.git"] }',
        '```',
        '',
        "OpenCode loads the plugin module on startup: it registers the skills directory through a config hook (no symlinks needed) and reads commands/agents translated under `.opencode/`. Consult the OpenCode plugin docs if this doesn't match your installed version.",
        '',
      ].join('\n'),
    )
  })
})

describe('agent-plugins installDoc mcp condition (Finding 2)', () => {
  it('does not list mcp.json in "What gets emitted" when mcp config is malformed (no mcpServers key)', () => {
    const dir = tmpFixture('name: malformed-mcp\nversion: 1.0.0\ndescription: malformed mcp fixture\n')
    // A real .mcp.json with the WRONG shape (servers instead of mcpServers) so the
    // isPlainObject(mcp.mcpServers) branch of wouldEmitMcp is what this test exercises.
    writeFileSync(join(dir, '.mcp.json'), JSON.stringify({ servers: {} }) + '\n')
    const malformedModel = buildModel(dir)
    expect(malformedModel.mcp).toBeDefined()
    const body = agentPlugins.installDoc!(malformedModel)
    // The installDoc should not list mcp.json in the emitted section when mcpManifest would return nothing
    const emittedSection = body.split('## Installing')[0]
    expect(emittedSection).not.toContain('`mcp.json`')
    expect(emittedSection).toContain('`plugin.json`')
  })

  it('lists mcp.json in "What gets emitted" for the kitchen-sink model which has valid mcp servers', () => {
    const body = agentPlugins.installDoc!(model)
    const emittedSection = body.split('## Installing')[0]
    expect(emittedSection).toContain('`mcp.json`')
  })
})

describe('opencode installDoc bootstrap conditionality (Finding 1)', () => {
  it('omits "injects bootstrap context" when bootstrap.kind is "none"', () => {
    const dir = tmpFixture('name: none-demo\nversion: 1.0.0\ndescription: bootstrap-none fixture\nbootstrap: none\n')
    const noneModel = buildModel(dir)
    const body = opencode.installDoc!(noneModel)
    expect(body).not.toContain('injects bootstrap context')
    expect(body).toContain("registers the plugin's skills directory")
  })

  it('includes "injects bootstrap context" when bootstrap.kind is "skill" (kitchen-sink model)', () => {
    const body = opencode.installDoc!(model)
    expect(body).toContain('injects bootstrap context')
  })
})

describe('pi installDoc bootstrap conditionality (Finding 1)', () => {
  it('omits "injects bootstrap context" when bootstrap.kind is "none"', () => {
    const dir = tmpFixture('name: none-demo\nversion: 1.0.0\ndescription: bootstrap-none fixture\nbootstrap: none\n')
    const noneModel = buildModel(dir)
    const body = pi.installDoc!(noneModel)
    expect(body).not.toContain('injects bootstrap context')
    expect(body).toContain("registers the plugin's skills directory")
  })

  it('includes "injects bootstrap context" when bootstrap.kind is "skill" (kitchen-sink model)', () => {
    const body = pi.installDoc!(model)
    expect(body).toContain('injects bootstrap context')
  })
})

describe('kimi installDoc caveat conditionality (representative)', () => {
  it('mentions sessionStart for the kitchen-sink fixture, whose bootstrap.kind is "skill"', () => {
    const body = kimi.installDoc!(model)
    expect(body).toContain('sessionStart')
  })

  it('omits the sessionStart sentence entirely for a none-bootstrap fixture', () => {
    const dir = tmpFixture('name: none-demo\nversion: 1.0.0\ndescription: bootstrap-none fixture\nbootstrap: none\n')
    const noneModel = buildModel(dir)
    const body = kimi.installDoc!(noneModel)
    expect(body).not.toContain('sessionStart')
    expect(body).not.toContain('## Caveats')
  })
})
