import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { execSync } from 'node:child_process'
import { mkdtempSync, existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { stringify } from 'yaml'
import { fileURLToPath } from 'node:url'
import { generate } from '../src/generate.js'

// Design decision 7 / spec decision 7's north-star acceptance test: prove
// moe-mint's config + overrides are expressive enough to regenerate
// superpowers' own hand-maintained per-harness manifests semantically
// (modulo documented, by-design differences). Comparison is parsed-JSON
// deep equality (`toEqual`), not raw bytes: JSON key order and formatting
// are explicitly not a goal (the upstream author's ruling, 2026-08-12 -- see
// Finding 3's Resolution in docs/history/2026-08-11-dogfood-findings.md) and
// are never asserted here. Reads the checkout via `git archive HEAD` (never
// touches its working tree or index -- archive reads straight from the object
// database regardless of what is currently checked out).
//
// TARGET, AND WHY IT IS STILL UPSTREAM. This is the one invariant in the
// package that can only be tested against upstream superpowers: the claim is
// "moe-mint reproduces manifests a human maintained by hand", and packages/core
// (the rebranded superpowers) will have its manifests GENERATED by moe-mint, so
// the comparison would become circular there. So the target is the pinned
// reference snapshot named in PARITY.md (`superpowers` @ b36e082), not
// packages/core and not upstream `main`.
//
// Two consequences of switching from upstream's live-`dev`-tip target to a
// pinned snapshot: `HEAD` replaces `dev` (a shallow reference clone has one
// commit on `main`), and the test is now a pinned regression test rather than a
// drift tripwire — which is the whole point of pinning, per PARITY.md's
// "snapshots are the spec, not upstream HEAD".
//
// ../.moe-references/ is gitignored and outside the repo, so this runs locally
// and skips in CI, exactly as upstream's version did. MOE_MINT_DOGFOOD_REPO
// overrides the location.
const DEFAULT_SUPERPOWERS_REPO = join(
  fileURLToPath(new URL('../../..', import.meta.url)),
  '..',
  '.moe-references',
  'superpowers',
)
const SUPERPOWERS_REPO = process.env.MOE_MINT_DOGFOOD_REPO ?? DEFAULT_SUPERPOWERS_REPO
const SUPERPOWERS_AVAILABLE = existsSync(join(SUPERPOWERS_REPO, '.git'))

// The hand-maintained manifests this test regenerates and compares. Also
// read into `originals` (below) before the corresponding paths are deleted
// from the working copy, since generate() would otherwise refuse to
// overwrite them (they aren't tracked in a prior moe-mint manifest, so
// they look like unrelated pre-existing files).
const COMPARED_FILES = [
  '.claude-plugin/plugin.json',
  '.claude-plugin/marketplace.json',
  '.codex-plugin/plugin.json',
  '.devin-plugin/plugin.json',
  '.kimi-plugin/plugin.json',
  '.cursor-plugin/plugin.json',
  'gemini-extension.json',
  '.agents/plugins/marketplace.json',
] as const
type ComparedFile = (typeof COMPARED_FILES)[number]

// Hand-maintained paths removed from the extracted working copy before
// generate() runs. Each one is either a manifest generate() is about to
// rewrite (and would otherwise refuse to clobber) or a hand-authored
// equivalent of a file moe-mint emits itself under a different name/path
// (package.json, .opencode/, .pi/, GEMINI.md). Everything else in the real
// tree (skills/, hooks/hooks.json, docs/, tests/, README.md, ...) is left in
// place: skills/ and hooks/hooks.json are component sources moe-mint
// reads, and the rest doesn't collide with anything generate() writes.
const HAND_MAINTAINED_PATHS = [
  '.claude-plugin',
  '.codex-plugin',
  '.cursor-plugin',
  '.devin-plugin',
  '.kimi-plugin',
  '.hermes-plugin',
  '.agents',
  'gemini-extension.json',
  'GEMINI.md',
  'package.json',
  '.opencode',
  '.pi',
]

interface ExpectedDifference {
  file: ComparedFile
  path: string
  reason: string
}

// Documented, by-design (or documented-gap) differences between generated
// and real output. Every entry is a top-level manifest key; the comparison
// below deletes that key from BOTH the generated and original objects
// before asserting deep equality, so an entry only masks the exact
// difference it names -- anything else still fails the test. This list is
// the acceptance criterion: an undocumented difference fails.
//
// Empty as of this branch. All three differences ever tolerated here --
// claude-code's and cursor's forced hooks pointer, and marketplace.json's
// hardcoded description -- are now closed: `harnesses.<name>.hooks: own`
// (see src/adapters/shared.ts's bootstrapEmitsHooks) lets superpowers keep
// its own hand-wired hooks instead of the generated pointer, and
// `marketplace.description` (issue #7) gives marketplaceManifest() an
// override hook. See docs/history/2026-08-11-dogfood-findings.md
// for the Resolution section recording how each one closed.
const EXPECTED_DIFFERENCES: ExpectedDifference[] = []

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path, 'utf8'))
}

// Deletes every EXPECTED_DIFFERENCES key registered for `file` from clones
// of both sides before comparison, so the deep-equal assertion below only
// ever ignores exactly the documented differences.
function withExpectedDifferencesRemoved(
  file: ComparedFile,
  generated: Record<string, unknown>,
  original: Record<string, unknown>,
): { generated: Record<string, unknown>; original: Record<string, unknown> } {
  const g = structuredClone(generated)
  const o = structuredClone(original)
  for (const diff of EXPECTED_DIFFERENCES) {
    if (diff.file !== file) continue
    delete g[diff.path]
    delete o[diff.path]
  }
  return { generated: g, original: o }
}

// Builds the moe-mint.yaml config that should regenerate superpowers'
// real manifests. Per-harness override VALUES are read directly off the
// real originals (rather than hand-transcribed) so a copy/paste slip in a
// long field -- kimi's multi-paragraph skillInstructions, codex's 14-key
// interface block -- can't silently pass or fail the test for the wrong
// reason. What's under test is the STRUCTURAL claim (design decision 7):
// given the right override values, does deepMerge + each adapter's emit()
// reproduce the exact real manifest shape? That's independent of where the
// override strings themselves came from.
function buildConfig(originals: Record<ComparedFile, Record<string, unknown>>): Record<string, unknown> {
  const claude = originals['.claude-plugin/plugin.json']
  const marketplace = originals['.claude-plugin/marketplace.json']
  const codex = originals['.codex-plugin/plugin.json']
  const devin = originals['.devin-plugin/plugin.json']
  const kimi = originals['.kimi-plugin/plugin.json']
  const cursor = originals['.cursor-plugin/plugin.json']
  const gemini = originals['gemini-extension.json']
  const agentsMarketplace = originals['.agents/plugins/marketplace.json'] as {
    interface: { displayName: string }
    plugins: unknown[]
  }
  const codexAuthor = codex.author as { url: string }

  return {
    name: claude.name,
    version: claude.version,
    description: claude.description,
    author: claude.author,
    homepage: claude.homepage,
    repository: claude.repository,
    license: claude.license,
    keywords: claude.keywords,
    bootstrap: { skill: 'using-superpowers' },
    // Closes Finding 1: marketplaceManifest() (src/adapters/claude-code.ts)
    // deep-merges this onto its hardcoded `Development marketplace for
    // ${config.name}` default, reproducing superpowers' hand-written copy.
    marketplace: { description: marketplace.description },
    harnesses: {
      // hooks: own -- superpowers hand-wires its own bootstrap hooks
      // (hooks/run-hook.cmd, hooks/session-start) directly under hooks/ rather
      // than the adapters' generated hooks/moe-mint/*.json, so neither
      // claude-code nor cursor should force their own hooks pointer into the
      // manifest. See src/adapters/shared.ts's bootstrapEmitsHooks.
      'claude-code': { hooks: 'own' },
      // cursor: hooks own (same reason as claude-code) plus a manifest patch.
      // display name and description are cursor-specific copy; hooks points at
      // superpowers' own hand-wired hooks-cursor.json -- with hooks: own,
      // pluginManifest() no longer supplies its own hooks pointer, so the
      // manifest patch carries the real value instead. Everything else
      // (author, homepage, repository, license, keywords) matches the shared
      // base fields above with no patch.
      cursor: {
        hooks: 'own',
        manifest: {
          displayName: cursor.displayName,
          description: cursor.description,
          hooks: cursor.hooks,
        },
      },
      // gemini: only description differs from the shared base (gemini's
      // extensionManifest doesn't include author/homepage/repository/
      // license/keywords at all).
      gemini: {
        manifest: {
          description: gemini.description,
        },
      },
      // codex: its own description + keyword set, an extra author.url
      // (deep-merged onto the shared {name,email}), and the full portal
      // `interface` block, which has no base-field equivalent.
      codex: {
        manifest: {
          description: codex.description,
          keywords: codex.keywords,
          author: { url: codexAuthor.url },
          interface: codex.interface,
        },
      },
      // devin: shares codex's description and keyword set but keeps the
      // shared plain {name,email} author (no url).
      devin: {
        manifest: {
          description: devin.description,
          keywords: devin.keywords,
        },
      },
      // kimi: its own (shorter) description, codex's keyword set, its
      // tool-mapping skillInstructions, and its own (smaller) interface
      // block. Uses repository: null to delete the inherited field.
      kimi: {
        manifest: {
          description: kimi.description,
          keywords: kimi.keywords,
          skillInstructions: kimi.skillInstructions,
          interface: kimi.interface,
          repository: null,
        },
      },
      // agents-marketplace: displayName patch plus a full replacement of the
      // plugins array (deepMerge replaces arrays wholesale) to add the
      // category field the default descriptor never sets.
      'agents-marketplace': {
        manifest: {
          interface: { displayName: agentsMarketplace.interface.displayName },
          plugins: agentsMarketplace.plugins,
        },
      },
    },
  }
}

if (!SUPERPOWERS_AVAILABLE) {
  console.log(
    `[dogfood] superpowers checkout not found at ${SUPERPOWERS_REPO} (or has no .git) -- skipping the dogfood test. Restore the pinned reference snapshot there (PARITY.md: \`superpowers\` @ b36e082, from github.com/obra/superpowers), or set MOE_MINT_DOGFOOD_REPO to point at an existing checkout, to run it locally.`,
  )
}

describe.skipIf(!SUPERPOWERS_AVAILABLE)('dogfood: regenerate superpowers hand-maintained manifests', () => {
  const originals: Record<ComparedFile, Record<string, unknown>> = {} as Record<ComparedFile, Record<string, unknown>>
  const generated: Record<ComparedFile, Record<string, unknown>> = {} as Record<ComparedFile, Record<string, unknown>>
  let dir: string

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'mint-dogfood-'))

    // Read-only on the source repo: `git archive` reads straight from the
    // object database at the `dev` ref, regardless of the checkout's
    // current branch or working-tree state, and never touches either.
    execSync(`git -C "${SUPERPOWERS_REPO}" archive HEAD | tar -x -C "${dir}"`)

    for (const file of COMPARED_FILES) {
      originals[file] = readJson(join(dir, file))
    }

    for (const path of HAND_MAINTAINED_PATHS) {
      rmSync(join(dir, path), { recursive: true, force: true })
    }

    writeFileSync(join(dir, 'moe-mint.yaml'), stringify(buildConfig(originals)))

    generate(dir)

    for (const file of COMPARED_FILES) {
      generated[file] = readJson(join(dir, file))
    }
  })

  afterAll(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  for (const file of COMPARED_FILES) {
    it(`regenerates ${file} to match the real manifest, modulo documented differences`, () => {
      const { generated: g, original: o } = withExpectedDifferencesRemoved(file, generated[file], originals[file])
      expect(g).toEqual(o)
    })
  }
})
