import { deepMerge } from '../fileset.js'
import type { GeneratedFile } from '../fileset.js'
import type { PluginModel, CommandRef } from '../model.js'
import type { HarnessAdapter, EmitResult } from './types.js'
import { json } from './shared.js'
import { generatedBootstrap, GENERATED_BOOTSTRAP_PATH } from '../bootstrap/generated.js'

const GENERATED_MARKER = '<!-- GENERATED by moe-mint — edit moe-mint.yaml instead -->'
const GENERATED_MARKER_TOML = '# GENERATED by moe-mint — edit moe-mint.yaml instead'

function extensionManifest(model: PluginModel): Record<string, unknown> {
  const { config } = model
  const manifest: Record<string, unknown> = {
    name: config.name,
    description: config.description,
    version: config.version,
    contextFileName: 'GEMINI.md',
  }
  const override = config.harnesses.settings.gemini?.manifest
  return override ? (deepMerge(manifest, override) as Record<string, unknown>) : manifest
}

// TOML basic-string escaping: backslash first (so an escaped backslash isn't
// re-escaped by the quote pass), then double-quote.
function tomlEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

// Gemini extension commands (commands/<name>.toml, extension root == plugin
// root) support only a single {{args}} placeholder, not Claude's positional
// $1/$2 syntax -- ground truth: gemini-cli docs/cli/custom-commands. $1-style
// syntax has no equivalent, so it is passed through verbatim with a warning
// rather than dropped or rejected.
function commandFile(cmd: CommandRef, warnings: string[]): GeneratedFile {
  if (/\$\d/.test(cmd.body)) {
    warnings.push(
      `command "${cmd.name}" uses positional arguments; Gemini supports only {{args}} — positional syntax passed through verbatim`,
    )
  }
  let body = cmd.body.replace(/\$ARGUMENTS(?!\w)/g, '{{args}}')
  // TOML basic multiline strings treat `\` as the start of an escape
  // sequence, so a literal backslash in the body (e.g. a regex or a Windows
  // path) must be doubled. This must run before the `"""` handling below --
  // otherwise the backslash that escaping introduces there would itself get
  // re-escaped.
  body = body.replace(/\\/g, '\\\\')
  // A literal `"""` in the body would prematurely close the TOML basic
  // multiline string. Escaping one of the three quotes (`""\"`) decodes back
  // to `"""` on parse, so the round-tripped prompt content is unchanged.
  if (body.includes('"""')) {
    body = body.replaceAll('"""', '""\\"')
    warnings.push(`command "${cmd.name}" body contains triple quotes; escaped for TOML`)
  }
  // Normalize the body's trailing newlines to exactly one before the closing
  // delimiter -- the source body already ends in `\n` (frontmatter parsing
  // leaves it), so appending a bare `\n"""` without trimming would leave a
  // blank line before the close.
  body = body.replace(/\n+$/, '')

  const lines = [GENERATED_MARKER_TOML]
  if (cmd.description) lines.push(`description = "${tomlEscape(cmd.description)}"`)
  lines.push('prompt = """')
  const content = `${lines.join('\n')}\n${body}\n"""\n`
  return { path: `commands/${cmd.name}.toml`, content }
}

function contextFile(model: PluginModel): string {
  const { config } = model
  if (config.bootstrap.kind === 'skill') {
    const skillName = config.bootstrap.skill
    const skill = model.skills.find((s) => s.name === skillName)
    if (!skill) {
      // buildModel validates the bootstrap skill exists before adapters run.
      throw new Error(`bootstrap skill "${skillName}" not found (buildModel should have validated this)`)
    }
    return `${GENERATED_MARKER}\n\n@./${skill.dir}/SKILL.md\n`
  }
  if (config.bootstrap.kind === 'generate') {
    return `${GENERATED_MARKER}\n\n@./${GENERATED_BOOTSTRAP_PATH}\n`
  }
  return `${GENERATED_MARKER}\n\nThis plugin provides skills in ${config.components.skills}/.\n`
}

// Ground truth per Design decision 4: `gemini extensions install URL`, with
// URL substituted from config.repository (falling back to `<your-repo>`
// when absent — never a fabricated listing).
function installDoc(model: PluginModel): string {
  const { config } = model
  const url = config.repository ?? '<your-repo>'

  const emitted = ['`gemini-extension.json`']
  if (config.bootstrap.kind === 'skill') {
    emitted.push("`GEMINI.md`, importing the bootstrap skill via Gemini's `@`-import syntax")
  } else if (config.bootstrap.kind === 'generate') {
    emitted.push(
      `\`GEMINI.md\`, importing the generated bootstrap file at \`${GENERATED_BOOTSTRAP_PATH}\` (also emitted) via Gemini's \`@\`-import syntax`,
    )
  } else {
    emitted.push("`GEMINI.md`, pointing at the plugin's skills directory (no bootstrap configured)")
  }
  if (model.commands.length) {
    emitted.push(
      `a \`commands/<name>.toml\` slash command for each command (${model.commands.map((c) => `\`${c.name}\``).join(', ')})`,
    )
  }

  const lines = [
    '## What gets emitted',
    '',
    ...emitted.map((e) => `- ${e}`),
    '',
    '## Installing',
    '',
    'Install the extension directly from its repository:',
    '',
    '```',
    `gemini extensions install ${url}`,
    '```',
    '',
    "`GEMINI.md` is loaded automatically as the extension's context file; each command becomes a `/name` slash command. Consult the Gemini CLI extensions docs if this command doesn't match your installed version.",
  ]

  if (model.commands.length > 0) {
    lines.push(
      '',
      '## Caveats',
      '',
      '- Gemini extension commands support only a single `{{args}}` placeholder; Claude-style positional arguments (`$1`, `$2`, ...) have no equivalent and are passed through verbatim into the command body.',
    )
  }

  return lines.join('\n')
}

export const gemini: HarnessAdapter = {
  name: 'gemini',
  support: {
    skills: 'full',
    commands: 'full',
    agents: 'none',
    hooks: 'none',
    mcp: 'none',
    bootstrap: 'full',
  },
  installDoc,
  emit(model: PluginModel): EmitResult {
    const { config } = model
    const warnings: string[] = []
    const files: GeneratedFile[] = [
      { path: 'gemini-extension.json', content: json(extensionManifest(model)) },
      { path: 'GEMINI.md', content: contextFile(model) },
      ...model.commands.map((c) => commandFile(c, warnings)),
    ]
    if (config.bootstrap.kind === 'generate') {
      files.push({ path: GENERATED_BOOTSTRAP_PATH, content: generatedBootstrap(model) })
    }

    const contextFileNameOverride = config.harnesses.settings.gemini?.manifest?.contextFileName
    if (typeof contextFileNameOverride === 'string' && contextFileNameOverride !== 'GEMINI.md') {
      warnings.push(
        `contextFileName override "${contextFileNameOverride}" does not match the emitted GEMINI.md; the harness will look for a missing file`,
      )
    }

    if (model.hooks !== undefined) warnings.push('hooks are not emitted for gemini')
    if (model.agents.length) warnings.push('agents are not emitted for gemini')
    if (model.mcp !== undefined) warnings.push('mcp servers are not emitted for gemini in v1 (Plan 3)')

    return { files, warnings }
  },
}
