import { stringify } from 'yaml'
import type { GeneratedFile } from '../fileset.js'
import type { PluginModel } from '../model.js'
import type { HarnessAdapter, EmitResult } from './types.js'
import { parseRepo } from './shared.js'
import { bootstrapContentPath } from '../bootstrap/node-package.js'
import { generatedBootstrap, GENERATED_BOOTSTRAP_PATH } from '../bootstrap/generated.js'

// Hermes' Python plugin module (`.hermes-plugin/__init__.py`), modeled
// directly on superpowers' own `.hermes-plugin/__init__.py`: a two-layout
// `_skills_dir()` probe (git-clone install: `.hermes-plugin/` and
// `<skillsdir>/` are siblings under the plugin root, so this module resolves
// `../<skillsdir>`; flattened install: `<skillsdir>/` sits next to this
// module) that raises loudly when neither layout matches, a
// `_strip_frontmatter` helper, and a `register(ctx)` that registers every
// skill with `ctx.register_skill(name, Path(skill_md))` -- note the
// `Path(...)`, not a plain string: passing a str raises AttributeError and
// hermes silently disables the whole plugin (verified 2026-07-23 against a
// real Hermes install). Bootstrap content is injected via `pre_llm_call`,
// the only documented injection path (on_session_start return values are
// ignored and ctx.inject_message refuses from that hook), gated on
// `is_first_turn` and registered through `ctx.register_hook`.
//
// Deliberately NOT emitted: a Hermes tool-mapping section (superpowers' own
// module documents how its Claude Code-flavored instructions map onto
// Hermes' native tools, e.g. `skill_view(...)`). That content is plugin-
// specific; plugins that want one should put it in their bootstrap skill's
// body instead.
//
// Placeholders: __PLUGIN_NAME__, __SKILLS_DIR__, __BOOTSTRAP_PATH__ (only
// used when bootstrap is active).
const PYTHON_INIT_TEMPLATE = [
  '# GENERATED by moe-mint — edit moe-mint.yaml instead',
  'import os',
  'import re',
  'import sys',
  'from pathlib import Path',
  '',
  'BOOTSTRAP_MARKER = \'<plugin-bootstrap plugin="__PLUGIN_NAME__">\'',
  '',
  '',
  'def _skills_dir():',
  '    """Locate the __SKILLS_DIR__/ tree for either supported install layout,',
  '    returning (skills_dir, plugin_root).',
  '',
  '    - git-clone install: `.hermes-plugin/` and `__SKILLS_DIR__/` are',
  '      siblings under the plugin root, so this module resolves',
  '      `../__SKILLS_DIR__` (plugin_root = one level up from this file).',
  '    - flattened install: `__SKILLS_DIR__/` sits next to this module',
  "      (plugin_root = this file's directory).",
  '',
  '    Raises loudly when neither matches -- a bootstrap that silently skips',
  '    is how a broken install masquerades as a working one.',
  '    """',
  '    here = os.path.dirname(os.path.realpath(__file__))',
  '    candidates = (',
  '        (os.path.realpath(os.path.join(here, "..", *"__SKILLS_DIR__".split("/"))), os.path.realpath(os.path.join(here, ".."))),',
  '        (os.path.realpath(os.path.join(here, *"__SKILLS_DIR__".split("/"))), here),',
  '    )',
  '    for skills_dir, plugin_root in candidates:',
  '        if os.path.isdir(skills_dir):',
  '            return skills_dir, plugin_root',
  '    raise RuntimeError(',
  '        "__PLUGIN_NAME__ plugin: cannot find the __SKILLS_DIR__/ tree "',
  '        f"(looked at {[c[0] for c in candidates]})."',
  '    )',
  '',
  '',
  'def _strip_frontmatter(content: str) -> str:',
  '    match = re.match(r"^---\\n[\\s\\S]*?\\n---\\n([\\s\\S]*)$", content)',
  '    return (match.group(1) if match else content).strip()',
  '',
  '',
  'def _build_bootstrap(plugin_root: str) -> str:',
  '    bootstrap_path = os.path.join(plugin_root, *"__BOOTSTRAP_PATH__".split("/"))',
  '    with open(bootstrap_path, encoding="utf-8") as f:',
  '        body = _strip_frontmatter(f.read())',
  '    return (',
  '        f"{BOOTSTRAP_MARKER}\\n"',
  '        "This plugin\'s bootstrap content is included below and is already "',
  '        "loaded for this session. Follow it now.\\n\\n"',
  '        f"{body}\\n"',
  '        "</plugin-bootstrap>"',
  '    )',
  '',
  '',
  'def register(ctx):',
  '    skills_dir, plugin_root = _skills_dir()',
  '',
  "    # Register every skill with Hermes' native loader so skill_view can",
  '    # load it on demand. Skills are registered before the bootstrap is',
  '    # built below so a broken bootstrap can never take skill registration',
  '    # down with it.',
  '    # register_skill requires a pathlib.Path — a str raises AttributeError and',
  '    # hermes silently disables the whole plugin (verified 2026-07-23).',
  '    for name in sorted(os.listdir(skills_dir)):',
  '        skill_md = os.path.join(skills_dir, name, "SKILL.md")',
  '        if os.path.isfile(skill_md):',
  '            ctx.register_skill(name, Path(skill_md))',
  '',
  '    # The bootstrap file is a separate, less load-bearing concern than the',
  '    # skills registered above -- a missing or unreadable bootstrap should',
  '    # degrade to "skills work, no session bootstrap" rather than disabling',
  '    # the whole plugin.',
  '    try:',
  '        bootstrap = _build_bootstrap(plugin_root)',
  '    except Exception as e:',
  '        print(',
  '            f"__PLUGIN_NAME__ plugin: bootstrap unavailable ({e}); "',
  '            "skills registered without session bootstrap",',
  '            file=sys.stderr,',
  '        )',
  '        return',
  '',
  '    # pre_llm_call returning {"context": ...} is the documented injection',
  "    # path; the context is appended to the first turn's user message.",
  '    def pre_llm_call(',
  '        session_id=None,',
  '        user_message=None,',
  '        conversation_history=None,',
  '        is_first_turn=None,',
  '        model=None,',
  '        platform=None,',
  '        **kwargs,',
  '    ):',
  '        if is_first_turn:',
  '            return {"context": bootstrap}',
  '        return None',
  '',
  '    ctx.register_hook("pre_llm_call", pre_llm_call)',
  '',
].join('\n')

// bootstrap: none variant -- skill registration only. There is no bootstrap
// content to inject, so BOOTSTRAP_MARKER, _strip_frontmatter,
// _build_bootstrap, and the pre_llm_call hook are omitted entirely rather
// than emitted as dead code.
const PYTHON_INIT_TEMPLATE_NO_BOOTSTRAP = [
  '# GENERATED by moe-mint — edit moe-mint.yaml instead',
  'import os',
  'from pathlib import Path',
  '',
  '',
  'def _skills_dir():',
  '    """Locate the __SKILLS_DIR__/ tree for either supported install layout,',
  '    returning (skills_dir, plugin_root).',
  '',
  '    - git-clone install: `.hermes-plugin/` and `__SKILLS_DIR__/` are',
  '      siblings under the plugin root, so this module resolves',
  '      `../__SKILLS_DIR__` (plugin_root = one level up from this file).',
  '    - flattened install: `__SKILLS_DIR__/` sits next to this module',
  "      (plugin_root = this file's directory).",
  '',
  '    Raises loudly when neither matches -- a bootstrap that silently skips',
  '    is how a broken install masquerades as a working one.',
  '    """',
  '    here = os.path.dirname(os.path.realpath(__file__))',
  '    candidates = (',
  '        (os.path.realpath(os.path.join(here, "..", *"__SKILLS_DIR__".split("/"))), os.path.realpath(os.path.join(here, ".."))),',
  '        (os.path.realpath(os.path.join(here, *"__SKILLS_DIR__".split("/"))), here),',
  '    )',
  '    for skills_dir, plugin_root in candidates:',
  '        if os.path.isdir(skills_dir):',
  '            return skills_dir, plugin_root',
  '    raise RuntimeError(',
  '        "__PLUGIN_NAME__ plugin: cannot find the __SKILLS_DIR__/ tree "',
  '        f"(looked at {[c[0] for c in candidates]})."',
  '    )',
  '',
  '',
  'def register(ctx):',
  '    skills_dir, _plugin_root = _skills_dir()',
  '',
  "    # Register every skill with Hermes' native loader so skill_view can",
  '    # load it on demand.',
  '    # register_skill requires a pathlib.Path — a str raises AttributeError and',
  '    # hermes silently disables the whole plugin (verified 2026-07-23).',
  '    for name in sorted(os.listdir(skills_dir)):',
  '        skill_md = os.path.join(skills_dir, name, "SKILL.md")',
  '        if os.path.isfile(skill_md):',
  '            ctx.register_skill(name, Path(skill_md))',
  '',
].join('\n')

function initPyModule(model: PluginModel): string {
  const bootstrapPath = bootstrapContentPath(model)
  const template = bootstrapPath !== undefined ? PYTHON_INIT_TEMPLATE : PYTHON_INIT_TEMPLATE_NO_BOOTSTRAP
  return template
    .replaceAll('__PLUGIN_NAME__', model.config.name)
    .replaceAll('__SKILLS_DIR__', model.config.components.skills)
    .replaceAll('__BOOTSTRAP_PATH__', bootstrapPath ?? '')
}

// `.hermes-plugin/plugin.yaml` -- hand-assembled (not pure yaml.stringify)
// because the generated-file marker must be a `#` comment and the `yaml`
// package's stringify doesn't emit comments: marker line, then
// stringify(...) of the manifest object.
function pluginYaml(model: PluginModel): string {
  const { config } = model
  const manifest: Record<string, unknown> = {
    name: config.name,
    version: config.version,
    description: config.description,
  }
  if (config.author) manifest.author = config.author.name
  if (bootstrapContentPath(model) !== undefined) manifest.provides_hooks = ['pre_llm_call']
  return '# GENERATED by moe-mint — edit moe-mint.yaml instead\n' + stringify(manifest)
}

function pluginYamlFile(model: PluginModel): GeneratedFile {
  return { path: '.hermes-plugin/plugin.yaml', content: pluginYaml(model) }
}

function initPyFile(model: PluginModel): GeneratedFile {
  return { path: '.hermes-plugin/__init__.py', content: initPyModule(model) }
}

// Ground truth per Design decision 4: `hermes plugins install REPO --enable`,
// with REPO substituted from config.repository — `owner/repo` shorthand on
// github.com, the full http(s) URL for any other supported host (Hermes
// installs from either shape) — and a `<your-repo>` placeholder otherwise
// (never a fabricated listing).
function installDoc(model: PluginModel): string {
  const { config } = model
  const ref = parseRepo(config.repository)
  const repo = ref ? (ref.host === 'github.com' ? ref.ownerRepo : ref.url) : '<your-repo>'

  const emitted = [
    "`.hermes-plugin/plugin.yaml` and `.hermes-plugin/__init__.py`, which register every skill natively and (when bootstrap is configured) inject bootstrap content via `pre_llm_call`",
  ]
  if (config.bootstrap.kind === 'generate') {
    emitted.push(`the generated bootstrap file at \`${GENERATED_BOOTSTRAP_PATH}\``)
  }

  const lines = [
    '## What gets emitted',
    '',
    ...emitted.map((e) => `- ${e}`),
    '',
    '## Installing',
    '',
    '```',
    `hermes plugins install ${repo} --enable`,
    '```',
    '',
    "Hermes registers every skill natively via `register_skill`; when bootstrap is configured, the plugin injects it on the first turn through the `pre_llm_call` hook. Consult Hermes' plugin docs if this command doesn't match your installed version.",
    '',
    '## Caveats',
    '',
    `- Hermes prints \`${config.name} doesn't contain plugin.yaml or __init__.py. It may not be a valid Hermes plugin.\` during install. That warning is expected — moe-mint emits those files under \`.hermes-plugin/\`, which Hermes locates after the warning. Confirm the install with \`hermes plugins list --plain --no-bundled\`.`,
    `- \`hermes plugins enable\` takes the manifest name (\`${config.name}\`), not the checkout directory name — the two differ whenever the directory is named something else.`,
    '- Hermes imports `.hermes-plugin/__init__.py` as a Python package on every load, so Python writes `.hermes-plugin/__pycache__/` next to it. Add `__pycache__/` to your `.gitignore`; moe-mint never edits user files, so it will not do this for you.',
  ]
  return lines.join('\n')
}

export const hermes: HarnessAdapter = {
  name: 'hermes',
  support: {
    skills: 'full',
    commands: 'none',
    agents: 'none',
    hooks: 'none',
    mcp: 'none',
    bootstrap: 'full',
  },
  installDoc,
  emit(model: PluginModel): EmitResult {
    const warnings: string[] = []
    const files: GeneratedFile[] = [pluginYamlFile(model), initPyFile(model)]
    // hermes' __init__.py reads GENERATED_BOOTSTRAP_PATH at runtime (via
    // bootstrapContentPath above) in bootstrap.generate mode -- it must also
    // emit that file itself so the path it reads actually exists when
    // hermes is the only active in-process adapter.
    if (model.config.bootstrap.kind === 'generate') {
      files.push({ path: GENERATED_BOOTSTRAP_PATH, content: generatedBootstrap(model) })
    }

    if (model.commands.length) warnings.push('commands are not emitted for hermes')
    if (model.agents.length) warnings.push('agents are not emitted for hermes')
    if (model.hooks !== undefined) warnings.push('hooks are not emitted for hermes')
    if (model.mcp !== undefined) warnings.push('mcp servers are not emitted for hermes')

    return { files, warnings }
  },
}
