import { stringify } from 'yaml'
import type { GeneratedFile } from '../fileset.js'
import type { PluginModel, CommandRef, AgentRef } from '../model.js'
import type { HarnessAdapter, EmissionLimitation } from './types.js'
import { deriveEmittedCapabilities } from '../platform/capabilities.js'
import { opencodeServerExport, opencodePluginPath, bootstrapContentPath } from '../bootstrap/node-package.js'
import { generatedBootstrap, GENERATED_BOOTSTRAP_PATH } from '../bootstrap/generated.js'

// Marker text for command/agent files, placed as a `#` YAML comment inside
// the frontmatter block -- see yamlFrontmatter below for why.
const GENERATED_COMMENT = 'GENERATED by moe-mint — edit moe-mint.yaml instead'

// OpenCode's plugin loader (`.opencode/plugins/<name>.js`) uses a module-level
// tri-state bootstrap cache, a marker-guarded injection into the first user
// message (never the system prompt -- see the mechanics comment in
// OPENCODE_PLUGIN_TEMPLATE below), and a config hook that registers the
// plugin's skills directory without requiring symlinks.
//
// Written as plain string arrays (not TS template literals): the emitted
// JS itself uses `${...}`-style concatenation internally via `+`, so a host
// template literal would collide with TS interpolation the same way bash's
// `${...}` would (see bootstrap/shell-hook.ts for the same rationale).
// Placeholders: __PLUGIN_NAME__, __PASCAL_NAME__, __SKILLS_DIR__,
// __BOOTSTRAP_PATH__ (only used when bootstrap is active).
const OPENCODE_PLUGIN_TEMPLATE = [
  '// __PLUGIN_NAME__ plugin for OpenCode — registers the skills directory and injects bootstrap context into the first user message.',
  '// GENERATED by moe-mint — edit moe-mint.yaml instead',
  '',
  "import path from 'path'",
  "import fs from 'fs'",
  "import { fileURLToPath } from 'url'",
  '',
  'const __dirname = path.dirname(fileURLToPath(import.meta.url))',
  '',
  '// Minimal frontmatter stripper (dependency-free rather than pulling in a',
  '// markdown/frontmatter package for a single bootstrap-file read).',
  'const extractAndStripFrontmatter = (content) => {',
  '  const match = content.match(/^---\\n([\\s\\S]*?)\\n---\\n([\\s\\S]*)$/)',
  '  if (!match) return { frontmatter: {}, content }',
  '  const frontmatterStr = match[1]',
  '  const body = match[2]',
  '  const frontmatter = {}',
  "  for (const line of frontmatterStr.split('\\n')) {",
  "    const colonIdx = line.indexOf(':')",
  '    if (colonIdx > 0) {',
  '      const key = line.slice(0, colonIdx).trim()',
  '      const value = line.slice(colonIdx + 1).trim().replace(/^["\']|["\']$/g, \'\')',
  '      frontmatter[key] = value',
  '    }',
  '  }',
  '  return { frontmatter, content: body }',
  '}',
  '',
  "const skillsDir = path.resolve(__dirname, '../../__SKILLS_DIR__')",
  'const BOOTSTRAP_MARKER = \'<plugin-bootstrap plugin="__PLUGIN_NAME__">\'',
  '',
  '// Module-level cache for bootstrap content. The bootstrap file does not',
  '// change during a session, so reading and parsing it once eliminates',
  '// redundant fs work on every agent step.',
  'let _bootstrapCache = undefined // undefined = not yet loaded, null = file missing',
  '',
  'export const __PASCAL_NAME__Plugin = async ({ client, directory }) => {',
  '  const getBootstrapContent = () => {',
  '    if (_bootstrapCache !== undefined) return _bootstrapCache',
  '',
  "    const bootstrapPath = path.resolve(__dirname, '../../__BOOTSTRAP_PATH__')",
  '    if (!fs.existsSync(bootstrapPath)) {',
  '      _bootstrapCache = null',
  '      return null',
  '    }',
  '',
  "    const fullContent = fs.readFileSync(bootstrapPath, 'utf8')",
  '    const { content } = extractAndStripFrontmatter(fullContent)',
  '',
  "    _bootstrapCache = BOOTSTRAP_MARKER + '\\n' + content + '\\n</plugin-bootstrap>'",
  '    return _bootstrapCache',
  '  }',
  '',
  '  return {',
  "    // Inject the plugin's skills path into live config so OpenCode discovers",
  '    // its skills without requiring manual symlinks or config file edits.',
  '    config: async (config) => {',
  '      config.skills = config.skills || {}',
  '      config.skills.paths = config.skills.paths || []',
  '      if (!config.skills.paths.includes(skillsDir)) {',
  '        config.skills.paths.push(skillsDir)',
  '      }',
  '    },',
  '',
  '    // Inject bootstrap into the first user message of each session, guarded',
  '    // by a marker substring so re-running the transform on an already',
  '    // transformed message array never injects twice.',
  "    'experimental.chat.messages.transform': async (_input, output) => {",
  '      const bootstrap = getBootstrapContent()',
  '      if (!bootstrap || !output.messages.length) return',
  "      const firstUser = output.messages.find((m) => m.info.role === 'user')",
  '      if (!firstUser || !firstUser.parts.length) return',
  '',
  "      if (firstUser.parts.some((p) => p.type === 'text' && p.text.includes(BOOTSTRAP_MARKER))) return",
  '',
  '      const ref = firstUser.parts[0]',
  "      firstUser.parts.unshift({ ...ref, type: 'text', text: bootstrap })",
  '    },',
  '  }',
  '}',
  '',
].join('\n')

// bootstrap: none variant -- config-hook-only plugin. The bootstrap cache
// and message-transform hook are omitted entirely rather than emitted as
// dead code, since there is no bootstrap content to inject.
const OPENCODE_PLUGIN_TEMPLATE_NO_BOOTSTRAP = [
  "// __PLUGIN_NAME__ plugin for OpenCode — registers the skills directory.",
  '// GENERATED by moe-mint — edit moe-mint.yaml instead',
  '',
  "import path from 'path'",
  "import { fileURLToPath } from 'url'",
  '',
  'const __dirname = path.dirname(fileURLToPath(import.meta.url))',
  '',
  "const skillsDir = path.resolve(__dirname, '../../__SKILLS_DIR__')",
  '',
  'export const __PASCAL_NAME__Plugin = async ({ client, directory }) => {',
  '  return {',
  "    // Inject the plugin's skills path into live config so OpenCode discovers",
  '    // its skills without requiring manual symlinks or config file edits.',
  '    config: async (config) => {',
  '      config.skills = config.skills || {}',
  '      config.skills.paths = config.skills.paths || []',
  '      if (!config.skills.paths.includes(skillsDir)) {',
  '        config.skills.paths.push(skillsDir)',
  '      }',
  '    },',
  '  }',
  '}',
  '',
].join('\n')

// Plugin names are validated as /^[a-z0-9][a-z0-9-]*$/ (config.ts), which
// permits a leading digit -- not a valid start for a JS identifier. Prefix
// with `_` in that case so `export const <PascalName>Plugin` is always
// syntactically valid.
function toPascalCase(name: string): string {
  const pascal = name
    .split('-')
    .filter(Boolean)
    .map((part) => (part[0] ?? '').toUpperCase() + part.slice(1))
    .join('')
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal
}

function pluginModule(model: PluginModel): string {
  const bootstrapPath = bootstrapContentPath(model)
  const template = bootstrapPath !== undefined ? OPENCODE_PLUGIN_TEMPLATE : OPENCODE_PLUGIN_TEMPLATE_NO_BOOTSTRAP
  return template
    .replaceAll('__PLUGIN_NAME__', model.config.name)
    .replaceAll('__PASCAL_NAME__', toPascalCase(model.config.name))
    .replaceAll('__SKILLS_DIR__', model.config.components.skills)
    .replaceAll('__BOOTSTRAP_PATH__', bootstrapPath ?? '')
}

// Builds a `---\n# <marker>\n<fields>---\n` frontmatter block with the
// generated-file marker as a `#` YAML comment on the line right after the
// opening `---`, instead of as an HTML comment before it.
//
// Deviation from the plan's literal "marker line 1 (HTML comment), then
// frontmatter" wording: OpenCode parses command/agent frontmatter with
// gray-matter, which (like this repo's own frontmatter.ts) requires `---`
// to be the file's first three bytes -- a leading comment line would make
// the whole file's frontmatter invisible, silently dropping `description`
// and `mode: subagent` and defeating the point of translating these files
// at all (verified against opencode.ai/docs/commands and /agents, and
// gray-matter's parsing algorithm). Keeping `---` as true line 1 and moving
// the marker inside the block as a YAML comment satisfies both "every
// generated file is visibly marked" and "OpenCode can actually parse this
// file" -- see task-3-report.md for the full writeup.
function yamlFrontmatter(fields: Record<string, string>): string {
  const lines = ['---', `# ${GENERATED_COMMENT}`]
  if (Object.keys(fields).length) {
    lines.push(stringify(fields, { lineWidth: 0 }).trimEnd())
  }
  lines.push('---')
  return lines.join('\n') + '\n'
}

function commandFile(cmd: CommandRef): GeneratedFile {
  const fields: Record<string, string> = {}
  if (cmd.description) fields.description = cmd.description
  return { path: `.opencode/command/${cmd.name}.md`, content: yamlFrontmatter(fields) + cmd.body }
}

function agentFile(agent: AgentRef): GeneratedFile {
  const fields: Record<string, string> = {}
  if (agent.description) fields.description = agent.description
  fields.mode = 'subagent'
  return { path: `.opencode/agent/${agent.name}.md`, content: yamlFrontmatter(fields) + agent.body }
}

// Ground truth per Design decision 4: add `"plugin": ["<name>@git+URL.git"]`
// to opencode.json, with URL substituted from config.repository (falling
// back to `<your-repo>` when absent — never a fabricated listing).
function installDoc(model: PluginModel): string {
  const { config } = model
  const url = config.repository ?? '<your-repo>'
  const pluginPath = opencodePluginPath(config.name)

  const emitted = [
    'a `./server` export contribution for the artifact\'s composed root `package.json`',
  ]
  const bootstrapClause = config.bootstrap.kind !== 'none'
    ? 'the OpenCode plugin module that registers the plugin\'s skills directory and injects bootstrap context'
    : 'the OpenCode plugin module that registers the plugin\'s skills directory'
  emitted.push(`\`${pluginPath}\`, ${bootstrapClause}`)
  if (model.commands.length) {
    emitted.push(
      `a \`.opencode/command/<name>.md\` file for each command (${model.commands.map((c) => `\`${c.name}\``).join(', ')})`,
    )
  }
  if (model.agents.length) {
    emitted.push(
      `a \`.opencode/agent/<name>.md\` file for each agent (${model.agents.map((a) => `\`${a.name}\``).join(', ')})`,
    )
  }
  if (config.bootstrap.kind === 'generate') {
    emitted.push(`the generated bootstrap file at \`${GENERATED_BOOTSTRAP_PATH}\``)
  }

  const lines = [
    '## What gets emitted',
    '',
    ...emitted.map((e) => `- ${e}`),
    '',
    '## Installing',
    '',
    "Add the plugin to your project's `opencode.json`:",
    '',
    '```json',
    `{ "plugin": ["${config.name}@git+${url}.git"] }`,
    '```',
    '',
    "OpenCode loads the plugin module on startup: it registers the skills directory through a config hook (no symlinks needed) and reads commands/agents translated under `.opencode/`. Consult the OpenCode plugin docs if this doesn't match your installed version.",
    '',
  ]
  return lines.join('\n')
}

export const opencode: HarnessAdapter = Object.freeze({
  name: 'opencode',
  support: {
    skills: 'full',
    commands: 'full',
    agents: 'partial',
    hooks: 'none',
    mcp: 'none',
    bootstrap: 'full',
    rules: 'none',
    variables: 'none',
  },
  skillsOutputDir: '.opencode/skills',
  installDoc,
  emit(model: PluginModel) {
    const limitations: EmissionLimitation[] = []
    const files: GeneratedFile[] = [
      { path: opencodePluginPath(model.config.name), content: pluginModule(model) },
      ...model.commands.map(commandFile),
      ...model.agents.map(agentFile),
    ]
    // opencode's plugin module reads GENERATED_BOOTSTRAP_PATH at runtime
    // (via bootstrapContentPath above) in bootstrap.generate mode -- it must
    // also emit that file itself so the path it reads actually exists when
    // opencode is the only active in-process adapter.
    if (model.config.bootstrap.kind === 'generate') {
      files.push({ path: GENERATED_BOOTSTRAP_PATH, content: generatedBootstrap(model) })
    }

    if (model.hooks !== undefined) limitations.push({ code: 'COMPONENT_OMITTED', component: 'hooks', message: 'hooks are not emitted for opencode' })
    if (model.mcp !== undefined) limitations.push({ code: 'COMPONENT_OMITTED', component: 'mcp', message: 'mcp servers are not emitted for opencode in v1' })
    if (model.agents.some((a) => a.tools !== undefined)) {
      limitations.push({ code: 'SETTING_DROPPED', component: 'agents', message: 'agent tool restrictions are not translated for opencode' })
    }

    return {
      files,
      limitations,
      emittedCapabilities: deriveEmittedCapabilities('opencode', model, files),
      packageContribution: { owner: 'opencode' as const, exports: opencodeServerExport(model.config.name) },
    }
  },
})
