import type { GeneratedFile } from '../fileset.js'
import type { PluginModel } from '../model.js'
import type { ComponentSupport, HarnessAdapter, EmissionLimitation } from './types.js'
import { deriveEmittedCapabilities } from '../platform/capabilities.js'
import { parseRepo } from './shared.js'
import { piDiscoveryMetadata, piExtensionPath, bootstrapContentPath } from '../bootstrap/node-package.js'
import { generatedBootstrap, GENERATED_BOOTSTRAP_PATH } from '../bootstrap/generated.js'

// Pi's extension loader (`.pi/extensions/<name>.ts`) uses `resources_discover`
// registers the plugin's skills directory; a lifecycle flag is armed on
// `session_start`/`session_compact` and disarmed on `agent_end`; a `context`
// handler injects bootstrap content into the conversation once per armed
// window, guarded by a marker-substring scan of already-present messages
// (`messageContainsBootstrap`) and spliced in after any leading
// `compactionSummary` messages (`firstNonCompactionSummaryIndex`) rather
// than always at index 0.
//
// Deliberately NOT emitted: a Pi tool-mapping section. Plugin-specific docs can
// explain how Claude Code-flavored instructions map onto
// Pi's native tools -- `read`/`write`/`edit`/`bash`, no `Skill` tool, no
// `Task` tool). That content is inherently plugin-specific (it describes
// what the plugin's *skills* ask the agent to do), and overrides can't
// inject into a generated TS file. Plugins that want a Pi tool-mapping
// section should put it in their bootstrap skill's body instead.
//
// Written as plain string arrays (not TS template literals), same rationale
// as the opencode template: the emitted TS's own template-literal-free
// string building keeps a host template literal from colliding with TS
// interpolation. Placeholders: __PLUGIN_NAME__, __SKILLS_DIR__,
// __BOOTSTRAP_PATH__ (only used when bootstrap is active).
const PI_EXTENSION_TEMPLATE = [
  '// __PLUGIN_NAME__ extension for Pi — registers the skills directory and injects bootstrap context into the conversation.',
  '// GENERATED by moe-mint — edit moe-mint.yaml instead',
  '',
  "import { readFileSync } from 'node:fs'",
  "import { dirname, resolve } from 'node:path'",
  "import { fileURLToPath } from 'node:url'",
  "import type { ExtensionAPI } from '@earendil-works/pi-coding-agent'",
  '',
  'const BOOTSTRAP_MARKER = \'<plugin-bootstrap plugin="__PLUGIN_NAME__">\'',
  '',
  'const extensionDir = dirname(fileURLToPath(import.meta.url))',
  "const packageRoot = resolve(extensionDir, '../..')",
  "const skillsDir = resolve(packageRoot, '__SKILLS_DIR__')",
  "const bootstrapPath = resolve(packageRoot, '__BOOTSTRAP_PATH__')",
  '',
  '// Module-level cache for bootstrap content. The bootstrap file does not',
  '// change during a session, so reading and stripping it once eliminates',
  '// redundant fs work on every context call.',
  'let cachedBootstrap: string | null | undefined',
  '',
  'export default function extension(pi: ExtensionAPI) {',
  '  let injectBootstrap = true',
  '',
  "  pi.on('resources_discover', async () => ({",
  '    skillPaths: [skillsDir],',
  '  }))',
  '',
  "  pi.on('session_start', async () => {",
  '    injectBootstrap = true',
  '  })',
  '',
  "  pi.on('session_compact', async () => {",
  '    injectBootstrap = true',
  '  })',
  '',
  "  pi.on('agent_end', async () => {",
  '    injectBootstrap = false',
  '  })',
  '',
  "  pi.on('context', async (event) => {",
  '    if (!injectBootstrap) return',
  '    if (event.messages.some(messageContainsBootstrap)) return',
  '',
  '    const bootstrap = getBootstrapContent()',
  '    if (!bootstrap) return',
  '',
  '    const bootstrapMessage = {',
  "      role: 'user' as const,",
  "      content: [{ type: 'text' as const, text: bootstrap }],",
  '      timestamp: Date.now(),',
  '    }',
  '',
  '    const insertAt = firstNonCompactionSummaryIndex(event.messages)',
  '    return {',
  '      messages: [',
  '        ...event.messages.slice(0, insertAt),',
  '        bootstrapMessage,',
  '        ...event.messages.slice(insertAt),',
  '      ],',
  '    }',
  '  })',
  '}',
  '',
  'function getBootstrapContent(): string | null {',
  '  if (cachedBootstrap !== undefined) return cachedBootstrap',
  '',
  '  try {',
  "    const fullContent = readFileSync(bootstrapPath, 'utf8')",
  '    const body = stripFrontmatter(fullContent)',
  "    cachedBootstrap = BOOTSTRAP_MARKER + '\\n' + body + '\\n</plugin-bootstrap>'",
  '    return cachedBootstrap',
  '  } catch {',
  '    cachedBootstrap = null',
  '    return null',
  '  }',
  '}',
  '',
  'function stripFrontmatter(content: string): string {',
  '  const match = content.match(/^---\\n[\\s\\S]*?\\n---\\n([\\s\\S]*)$/)',
  '  return (match ? match[1] : content).trim()',
  '}',
  '',
  'function messageContainsBootstrap(message: unknown): boolean {',
  '  const content = (message as { content?: unknown }).content',
  "  if (typeof content === 'string') return content.includes(BOOTSTRAP_MARKER)",
  '  if (!Array.isArray(content)) return false',
  '  return content.some((part) => {',
  '    return (',
  '      part &&',
  "      typeof part === 'object' &&",
  "      (part as { type?: unknown }).type === 'text' &&",
  "      typeof (part as { text?: unknown }).text === 'string' &&",
  '      (part as { text: string }).text.includes(BOOTSTRAP_MARKER)',
  '    )',
  '  })',
  '}',
  '',
  'function firstNonCompactionSummaryIndex(messages: unknown[]): number {',
  '  let index = 0',
  "  while ((messages[index] as { role?: unknown } | undefined)?.role === 'compactionSummary') {",
  '    index += 1',
  '  }',
  '  return index',
  '}',
  '',
].join('\n')

// bootstrap: none variant -- resources_discover only. There is no bootstrap
// content to inject, so the cache, lifecycle handlers, and context handler
// are omitted entirely rather than emitted as dead code.
const PI_EXTENSION_TEMPLATE_NO_BOOTSTRAP = [
  '// __PLUGIN_NAME__ extension for Pi — registers the skills directory.',
  '// GENERATED by moe-mint — edit moe-mint.yaml instead',
  '',
  "import { dirname, resolve } from 'node:path'",
  "import { fileURLToPath } from 'node:url'",
  "import type { ExtensionAPI } from '@earendil-works/pi-coding-agent'",
  '',
  'const extensionDir = dirname(fileURLToPath(import.meta.url))',
  "const packageRoot = resolve(extensionDir, '../..')",
  "const skillsDir = resolve(packageRoot, '__SKILLS_DIR__')",
  '',
  'export default function extension(pi: ExtensionAPI) {',
  "  pi.on('resources_discover', async () => ({",
  '    skillPaths: [skillsDir],',
  '  }))',
  '}',
  '',
].join('\n')

function extensionModule(model: PluginModel): string {
  const bootstrapPath = bootstrapContentPath(model)
  const template = bootstrapPath !== undefined ? PI_EXTENSION_TEMPLATE : PI_EXTENSION_TEMPLATE_NO_BOOTSTRAP
  return template
    .replaceAll('__PLUGIN_NAME__', model.config.name)
    .replaceAll('__SKILLS_DIR__', model.config.components.skills)
    .replaceAll('__BOOTSTRAP_PATH__', bootstrapPath ?? '')
}

function extensionFile(model: PluginModel): GeneratedFile {
  return { path: piExtensionPath(model.config.name), content: extensionModule(model) }
}

// Ground truth per Design decision 4: `pi install git:HOST/OWNER/REPO`,
// with HOST/OWNER/REPO substituted from config.repository when it parses as
// an http(s) repository URL — github.com, gitlab.com, self-hosted GitLab all
// take the same shape — and a `<your-repo>` placeholder otherwise (never a
// fabricated listing).
function installDoc(model: PluginModel): string {
  const { config } = model
  const ref = parseRepo(config.repository)
  const installTarget = ref ? `git:${ref.host}/${ref.ownerRepo}` : 'git:github.com/<your-repo>'
  const extensionPath = piExtensionPath(config.name)

  const emitted = [
    'Pi discovery metadata contributed under the composed root `package.json`\'s `pi` field',
  ]
  const bootstrapClause = config.bootstrap.kind !== 'none'
    ? 'the Pi extension module that registers the plugin\'s skills directory and injects bootstrap context'
    : 'the Pi extension module that registers the plugin\'s skills directory'
  emitted.push(`\`${extensionPath}\`, ${bootstrapClause}`)
  if (config.bootstrap.kind === 'generate') {
    emitted.push(`the generated bootstrap file at \`${GENERATED_BOOTSTRAP_PATH}\``)
  }

  const lines = [
    '## What gets emitted',
    '',
    ...emitted.map((e) => `- ${e}`),
    '',
    '## Installing',
    '',
    '```',
    `pi install ${installTarget}`,
    '```',
    '',
    "Pi discovers the extension and skills directory through the `pi` field in `package.json`. Consult Pi's extension docs if this command doesn't match your installed version.",
    '',
  ]
  return lines.join('\n')
}

export const pi: HarnessAdapter = Object.freeze({
  name: 'pi',
  support: {
    skills: 'full',
    commands: 'none',
    agents: 'none',
    hooks: 'none',
    mcp: 'none',
    bootstrap: 'full',
  } satisfies ComponentSupport,
  skillLayout: { outputDir: '.pi/skills', profile: 'pi', mode: 'rendered' as const },
  skillDelivery: 'rendered',
  installDoc,
  emit(model: PluginModel) {
    const limitations: EmissionLimitation[] = []
    const files: GeneratedFile[] = [
      extensionFile(model),
    ]
    // pi's extension module reads GENERATED_BOOTSTRAP_PATH at runtime (via
    // bootstrapContentPath above) in bootstrap.generate mode -- it must also
    // emit that file itself so the path it reads actually exists when pi is
    // the only active in-process adapter.
    if (model.config.bootstrap.kind === 'generate') {
      files.push({ path: GENERATED_BOOTSTRAP_PATH, content: generatedBootstrap(model) })
    }

    if (model.commands.length) limitations.push({ code: 'COMPONENT_OMITTED', component: 'commands', message: 'commands are not emitted for pi' })
    if (model.agents.length) limitations.push({ code: 'COMPONENT_OMITTED', component: 'agents', message: 'agents are not emitted for pi' })
    if (model.hooks !== undefined) limitations.push({ code: 'COMPONENT_OMITTED', component: 'hooks', message: 'hooks are not emitted for pi' })
    if (model.mcp !== undefined) limitations.push({ code: 'COMPONENT_OMITTED', component: 'mcp', message: 'mcp servers are not emitted for pi' })

    return {
      files,
      limitations,
      emittedCapabilities: deriveEmittedCapabilities('pi', model, files),
      packageContribution: { owner: 'pi' as const, pi: piDiscoveryMetadata(model) },
    }
  },
})
