// moe extension for Pi — registers the skills directory and injects bootstrap context into the conversation.
// GENERATED by moe-mint — edit moe-mint.yaml instead

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent'

const BOOTSTRAP_MARKER = '<plugin-bootstrap plugin="moe">'

const extensionDir = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(extensionDir, '../..')
const skillsDir = resolve(packageRoot, 'skills')
const bootstrapPath = resolve(packageRoot, 'skills/using-moe/SKILL.md')

// Module-level cache for bootstrap content. The bootstrap file does not
// change during a session, so reading and stripping it once eliminates
// redundant fs work on every context call.
let cachedBootstrap: string | null | undefined

export default function extension(pi: ExtensionAPI) {
  let injectBootstrap = true

  pi.on('resources_discover', async () => ({
    skillPaths: [skillsDir],
  }))

  pi.on('session_start', async () => {
    injectBootstrap = true
  })

  pi.on('session_compact', async () => {
    injectBootstrap = true
  })

  pi.on('agent_end', async () => {
    injectBootstrap = false
  })

  pi.on('context', async (event) => {
    if (!injectBootstrap) return
    if (event.messages.some(messageContainsBootstrap)) return

    const bootstrap = getBootstrapContent()
    if (!bootstrap) return

    const bootstrapMessage = {
      role: 'user' as const,
      content: [{ type: 'text' as const, text: bootstrap }],
      timestamp: Date.now(),
    }

    const insertAt = firstNonCompactionSummaryIndex(event.messages)
    return {
      messages: [
        ...event.messages.slice(0, insertAt),
        bootstrapMessage,
        ...event.messages.slice(insertAt),
      ],
    }
  })
}

function getBootstrapContent(): string | null {
  if (cachedBootstrap !== undefined) return cachedBootstrap

  try {
    const fullContent = readFileSync(bootstrapPath, 'utf8')
    const body = stripFrontmatter(fullContent)
    cachedBootstrap = BOOTSTRAP_MARKER + '\n' + body + '\n</plugin-bootstrap>'
    return cachedBootstrap
  } catch {
    cachedBootstrap = null
    return null
  }
}

function stripFrontmatter(content: string): string {
  const match = content.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/)
  return (match ? match[1] : content).trim()
}

function messageContainsBootstrap(message: unknown): boolean {
  const content = (message as { content?: unknown }).content
  if (typeof content === 'string') return content.includes(BOOTSTRAP_MARKER)
  if (!Array.isArray(content)) return false
  return content.some((part) => {
    return (
      part &&
      typeof part === 'object' &&
      (part as { type?: unknown }).type === 'text' &&
      typeof (part as { text?: unknown }).text === 'string' &&
      (part as { text: string }).text.includes(BOOTSTRAP_MARKER)
    )
  })
}

function firstNonCompactionSummaryIndex(messages: unknown[]): number {
  let index = 0
  while ((messages[index] as { role?: unknown } | undefined)?.role === 'compactionSummary') {
    index += 1
  }
  return index
}
