// moe-glass plugin for OpenCode — registers the skills directory.
// GENERATED by moe-mint — edit moe-mint.yaml instead

import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const skillsDir = path.resolve(__dirname, '../../.opencode/skills')

export const MoeGlassPlugin = async ({ client, directory }) => {
  return {
    // Inject the plugin's skills path into live config so OpenCode discovers
    // its skills without requiring manual symlinks or config file edits.
    config: async (config) => {
      config.skills = config.skills || {}
      config.skills.paths = config.skills.paths || []
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir)
      }
    },
  }
}
