import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { VERSION } from "../src/version.js";

const PACKAGE_ROOT = join(import.meta.dirname, "..");

function readJson(relPath: string): unknown {
  return JSON.parse(readFileSync(join(PACKAGE_ROOT, relPath), "utf-8"));
}

/**
 * Upstream this suite also asserted `.claude-plugin/plugin.json` and
 * `.claude-plugin/marketplace.json` carried the same version. Both are gone —
 * plugin manifests are generated by `@tc/moe-mint` and there is one root
 * marketplace — so what remains is the invariant that mattered:
 * `src/version.ts` must not drift from package.json.
 *
 * That invariant used to be enforced by generating version.ts from package.json
 * in a `prebuild`/`pretest` hook. Under turbo and `tsc -b` there is no lifecycle
 * hook to hang a generator on, so version.ts is checked in and this test is the
 * guard instead. private-journal-mcp shows what happens without one: its MCP
 * server reported a hardcoded `version: '1.0.0'` while its package.json said
 * 2.0.1.
 */
describe("version sources of truth", () => {
  const pkg = readJson("package.json") as { version: string };

  it("VERSION constant in src/version.ts equals package.json version", () => {
    expect(VERSION).toBe(pkg.version);
  });

  it("the MCP server reports the same version rather than a hardcoded literal", () => {
    const server = readFileSync(join(PACKAGE_ROOT, "src/mcp-server.ts"), "utf-8");
    expect(server).toContain("version: VERSION");
    expect(server).not.toMatch(/version:\s*'\d+\.\d+\.\d+'/);
  });
});
